#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# exits if any of your variables is not set
set -o nounset

wait-for-it -t 120 web:8000

# Run the main container command.
exec "$@"