# Generated by Django 1.11.17 on 2018-12-28 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import prerequisites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.CharField(max_length=50, unique=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('current_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='icons/')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(blank=True, choices=[(9, 9), (10, 10), (11, 11), (12, 12), (13, 'Adult')], null=True)),
                ('xp_adjustment', models.IntegerField(default=0)),
                ('xp_adjust_explanation', models.CharField(blank=True, max_length=255, null=True)),
                ('final_xp', models.PositiveIntegerField(blank=True, null=True)),
                ('final_grade', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('block', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Block')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Course')),
            ],
            options={
                'verbose_name': 'Student Course',
                'ordering': ['-semester', 'block'],
            },
        ),
        migrations.CreateModel(
            name='DateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_type', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExcludedDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('date_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.DateType')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('value', models.PositiveIntegerField(unique=True)),
            ],
            options={
                'ordering': ['value'],
            },
            bases=(models.Model, prerequisites.models.IsAPrereqMixin),
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('xp', models.PositiveIntegerField(help_text='The XP at which this rank is granted')),
                ('icon', models.ImageField(blank=True, help_text="A backup where fa_icon can't be used.  E.g. in the quest maps.", null=True, upload_to='icons/ranks/')),
                ('fa_icon', models.TextField(blank=True, help_text='html to render a font-awesome icon or icon stack etc.', null=True)),
            ],
            options={
                'ordering': ['xp'],
            },
            bases=(models.Model, prerequisites.models.IsAPrereqMixin),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(choices=[(1, 1), (2, 2)])),
                ('first_day', models.DateField(blank=True, null=True)),
                ('last_day', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('closed', models.BooleanField(default=False, help_text='All student courses in this semester have been closed         and final marks recorded.')),
            ],
            options={
                'get_latest_by': 'first_day',
                'ordering': ['first_day'],
            },
        ),
        migrations.AddField(
            model_name='excludeddate',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Semester'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='grade_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Grade', verbose_name='Grade'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.Semester'),
        ),
        migrations.AddField(
            model_name='coursestudent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='coursestudent',
            unique_together={('user', 'course', 'grade_fk'), ('semester', 'block', 'user')},
        ),
    ]
