# Generated by Django 2.0.9 on 2019-01-08 05:56

import datetime

from django.db import migrations, models

import courses.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20190101_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='closed',
            field=models.BooleanField(default=False, help_text='All student courses in this semester have been closed and final marks recorded.'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='first_day',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='last_day',
            field=models.DateField(blank=True, default=courses.models.default_end_date, null=True),
        ),
    ]
