# Generated by Django 2.0.13 on 2019-04-22 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20190107_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursestudent',
            name='grade',
        ),
    ]
