# Generated by Django 2.0.13 on 2019-08-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_markrange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markrange',
            name='minimum_mark',
            field=models.FloatField(default=72.5, help_text='Minimum mark as a percentage from 0 to 100 (or higher)'),
        ),
        migrations.AlterField(
            model_name='markrange',
            name='name',
            field=models.CharField(default='Chillax Line', max_length=50),
        ),
    ]
