# Generated by Django 2.0.13 on 2019-08-15 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190815_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='markrange',
            options={'ordering': ['minimum_mark']},
        ),
        migrations.AlterField(
            model_name='markrange',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which courses this field is relevant to; If left blank it will apply to all courses.', to='courses.Course'),
        ),
    ]
