# Generated by Django 2.2.9 on 2020-04-05 00:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_xp_for_100_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='number',
        ),
    ]
