# Generated by Django 2.2.12 on 2020-05-09 02:57

from django.db import migrations


def load_more_initial_data(apps, schema_editor):
    Course = apps.get_model('courses', 'Course')

    # Create a default course for new tenants
    if not Course.objects.exists():
        Course.objects.create(
            title="Default",
        )

    Rank = apps.get_model('courses', 'Rank')
    if not Rank.objects.exists():
        Rank.objects.create(
            name="Default",
            xp=0,
            fa_icon="fa fa-angle-up"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200508_1816'),
    ]

    operations = [
        migrations.RunPython(load_more_initial_data),
    ]
