# Generated by Django 2.2.12 on 2020-05-09 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_auto_20200508_1816'),
    ]

    operations = [
        # migrations.RunPython(load_more_initial_data),
    ]
