# Generated by Django 2.2.12 on 2020-05-09 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_auto_20200508_1957'),
    ]

    operations = [
        # migrations.RunPython(load_initial_data),
    ]
