# Generated by Django 2.2.14 on 2020-08-04 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_grades_initialdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='active',
        ),
    ]
