# Generated by Django 3.2.12 on 2022-06-09 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_remove_semester_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='course',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.course'),
        ),
    ]
