# Generated by Django 3.2.13 on 2022-06-14 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_alter_coursestudent_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.block'),
        ),
    ]
