# Generated by Django 3.2.14 on 2022-07-12 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_auto_20220614_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='excludeddate',
            name='label',
            field=models.CharField(blank=True, help_text='An optional label for this date.', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='excludeddate',
            name='date_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.datetype'),
        ),
    ]
