# Generated by Django 3.2.13 on 2022-07-22 05:03

import courses.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_auto_20220711_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='first_day',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='semester',
            name='last_day',
            field=models.DateField(default=courses.models.default_end_date, null=True),
        ),
    ]
