# Generated by Django 3.2.13 on 2022-08-12 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_auto_20220721_2203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={},
        ),
        migrations.RenameField(
            model_name='block',
            old_name='block',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='block',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='block',
            name='start_time',
        ),
        migrations.AddField(
            model_name='block',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
