# Generated by Django 3.2.13 on 2022-08-12 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_alter_coursestudent_grade_fk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='block',
            options={'ordering': ['name'], 'verbose_name': 'Group'},
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='block',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='courses.block', verbose_name='Group'),
        ),
    ]
