# Generated by Django 3.2.18 on 2023-08-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_auto_20220812_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='markrange',
            name='courses',
            field=models.ManyToManyField(blank=True, help_text='Which courses this Mark Range will be used for; if left blank it will apply to all courses.', to='courses.Course'),
        ),
    ]
