# Generated by Django 3.2.18 on 2023-11-23 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_markrange_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='excludeddate',
            name='date_type',
        ),
        migrations.DeleteModel(
            name='DateType',
        ),
    ]
