# Generated by Django 3.2.18 on 2024-01-28 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_delete_datetype_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestudent',
            name='xp_adjust_explanation',
            field=models.CharField(blank=True, help_text='An optional reminder why an XP Adjustment was provided.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='coursestudent',
            name='xp_adjustment',
            field=models.IntegerField(default=0, help_text="A one-time adjustment to the the user's XP for this course."),
        ),
    ]
