# Generated by Django 3.2.25 on 2024-05-31 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_alter_helptext_for_xp_adjustment_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='name',
            field=models.CharField(blank=True, help_text="If left blank, the semester will display it's First Day as a default name, in the form: mmm-YYYY.", max_length=50),
        ),
    ]
