# Generated by Django 5.2.17 on 2026-08-16 16:50

from django.db import migrations, models

from courses.fa_icon_utils import split_fa_icon_value


def split_fa_icon_into_name_and_modifiers(apps, schema_editor):
    """Convert each Rank's ``fa_icon`` from a whole class list (``fa fa-star``,
    ``fa fa-forward fa-rotate-270``) into a bare name in ``fa_icon`` plus any
    extra classes in ``fa_icon_modifiers``, so the icon picker's bare-name output
    matches what is stored."""
    Rank = apps.get_model("courses", "Rank")
    for rank in Rank.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
        name, modifiers = split_fa_icon_value(rank.fa_icon)
        rank.fa_icon = name
        rank.fa_icon_modifiers = modifiers
        rank.save(update_fields=["fa_icon", "fa_icon_modifiers"])


def rejoin_name_and_modifiers_into_fa_icon(apps, schema_editor):
    """Reverse: fold the bare name and modifiers back into a single ``fa fa-<name>``
    class list, so the field round-trips if this migration is unapplied."""
    Rank = apps.get_model("courses", "Rank")
    for rank in Rank.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
        classes = "fa fa-" + rank.fa_icon.strip()
        modifiers = (rank.fa_icon_modifiers or "").strip()
        rank.fa_icon = classes + " " + modifiers if modifiers else classes
        rank.save(update_fields=["fa_icon"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_semester_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="fa_icon_modifiers",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional extra Font Awesome classes applied to the icon, e.g. "fa-rotate-270" to rotate it.',
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="fa_icon",
            field=models.TextField(
                blank=True,
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options.',
                null=True,
            ),
        ),
        migrations.RunPython(
            split_fa_icon_into_name_and_modifiers,
            rejoin_name_and_modifiers_into_fa_icon,
        ),
    ]
