# Generated by Django 5.2.17 on 2026-08-16 17:52

import re

import django.core.validators
from django.db import migrations, models


# Every "fa-<x>" class token in a value. Also plucks the icon out of a value
# that was (against the old, misleading help text) typed as HTML.
_FA_TOKEN_RE = re.compile(r"fa-[\w-]+")

# Font Awesome 4.7.0 classes that modify an icon rather than name one, so the
# splitter keeps them as modifiers instead of mistaking one for the icon (a
# value like "fa fa-fw fa-star" names the icon "star", not "fw").
_FA_MODIFIER_PREFIXES = (
    "fa-lg", "fa-2x", "fa-3x", "fa-4x", "fa-5x", "fa-fw", "fa-ul", "fa-li",
    "fa-border", "fa-pull-", "fa-spin", "fa-pulse", "fa-rotate-", "fa-flip-",
    "fa-stack", "fa-inverse",
)


def _is_modifier(token):
    """True if a "fa-<x>" token is a modifier/sizing class, not an icon name."""
    return any(token == prefix or token.startswith(prefix) for prefix in _FA_MODIFIER_PREFIXES)


def split_fa_icon_value(raw):
    """Split a legacy ``Rank.fa_icon`` value into ``(bare_name, modifiers)``.

    Kept inside the migration (not imported from application code) so this
    one-time data transformation stays frozen. Handles every shape the field
    held: a full class list ``"fa fa-forward fa-rotate-270"`` -> ``("forward",
    "fa-rotate-270")``, modifiers before the icon ``"fa fa-fw fa-star"`` ->
    ``("star", "fa-fw")``, a plain ``"fa fa-star"`` -> ``("star", "")``, a
    prefix-only ``"fa-diamond"`` -> ``("diamond", "")``, an already-bare
    ``"star-o"`` -> ``("star-o", "")``, an icon buried in HTML
    ``'<i class="fa fa-star"></i>'`` -> ``("star", "")``, and empty/unparseable
    -> ``("", "")``. The icon is the first ``fa-<x>`` token that is not a known
    modifier; the rest are kept as modifiers.
    """
    raw = (raw or "").strip()
    if not raw:
        return "", ""

    fa_tokens = _FA_TOKEN_RE.findall(raw)
    if not fa_tokens:
        # No "fa-" token: an already-bare name like "star-o" (ignore a stray "fa").
        # Only accept a lone, clean token; anything else is left unset rather than
        # writing a junk value into the field.
        words = [word for word in raw.split() if word and word != "fa"]
        if len(words) == 1 and re.fullmatch(r"[a-z0-9-]+", words[0]) and not words[0].startswith("fa-"):
            return words[0], ""
        return "", ""

    icon = None
    modifiers = []
    for token in fa_tokens:
        if icon is None and not _is_modifier(token):
            icon = token[len("fa-"):]
        else:
            modifiers.append(token)
    return (icon or ""), " ".join(modifiers)


def split_fa_icon_into_name_and_modifiers(apps, schema_editor):
    """Convert each Rank's ``fa_icon`` from a whole class list into a bare name in
    ``fa_icon`` plus any extra classes in ``fa_icon_modifiers``, so the icon
    picker's bare-name output matches what is stored."""
    Rank = apps.get_model("courses", "Rank")
    for rank in Rank.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
        name, modifiers = split_fa_icon_value(rank.fa_icon)
        rank.fa_icon = name
        rank.fa_icon_modifiers = modifiers
        rank.save(update_fields=["fa_icon", "fa_icon_modifiers"])


def rejoin_name_and_modifiers_into_fa_icon(apps, schema_editor):
    """Reverse: fold the bare name and modifiers back into a single ``fa fa-<name>``
    class list, so the field round-trips if this migration is unapplied."""
    Rank = apps.get_model("courses", "Rank")
    for rank in Rank.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
        classes = "fa fa-" + rank.fa_icon.strip()
        modifiers = (rank.fa_icon_modifiers or "").strip()
        rank.fa_icon = classes + " " + modifiers if modifiers else classes
        rank.save(update_fields=["fa_icon"])


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_semester_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="fa_icon_modifiers",
            field=models.CharField(
                blank=True,
                default="",
                help_text='Optional extra Font Awesome classes applied to the icon, e.g. "fa-rotate-270" to rotate it.',
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9\\s-]*$",
                        'Enter Font Awesome modifier classes in lowercase, e.g. "fa-rotate-270".',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="fa_icon",
            field=models.TextField(
                blank=True,
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options.',
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!fa-)[a-z0-9-]*$",
                        'Enter a single Font Awesome icon name in lowercase, e.g. "star" (no "fa-" prefix, no spaces).',
                    )
                ],
            ),
        ),
        migrations.RunPython(
            split_fa_icon_into_name_and_modifiers,
            rejoin_name_and_modifiers_into_fa_icon,
        ),
    ]
