# Generated by Django 5.2.16 on 2026-08-18 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0030_rank_fa_icon_modifiers_alter_rank_fa_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="uses_marks",
            field=models.BooleanField(
                default=True,
                help_text='Uncheck to run this course on XP alone, with no percentage: students in it see what they have earned but are never shown a mark, and no mark is worked out for them anywhere. Useful for a course that shares a deck with graded ones but isn\'t itself graded. Only has any effect when "Use mark percentages" is on for the deck as a whole.',
                verbose_name="Use mark percentages",
            ),
        ),
    ]
