# Generated by Django 5.2.17 on 2026-08-24 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0031_course_uses_marks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rank",
            name="fa_icon",
            field=models.TextField(
                blank=True,
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options, or see the full list of <a target="_blank" rel="noopener" href="https://fontawesome.com/v4.7.0/icons/">Font Awesome 4.7.0 icons</a>.',
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!fa-)[a-z0-9-]*$",
                        'Enter a single Font Awesome icon name in lowercase, e.g. "star" (no "fa-" prefix, no spaces).',
                    )
                ],
            ),
        ),
    ]
