# Generated by Django 5.2.17 on 2026-09-02 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0033_repair_rank_fa_icon_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="excludeddate",
            name="date",
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name="excludeddate",
            constraint=models.UniqueConstraint(
                fields=("semester", "date"), name="unique_excluded_date_per_semester"
            ),
        ),
    ]
