# Generated by Django 5.2.17 on 2026-09-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0034_excluded_date_unique_per_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="markrange",
            name="color_headers",
            field=models.BooleanField(
                db_default=True,
                default=True,
                help_text="Students whose mark is in this range get this color in their header. This has no effect unless “Activate Header Colors by Mark” is on in Site Configuration. When unchecked, this range only appears on the graph in the Mark Calculations page.",
                verbose_name="Use this color in student headers",
            ),
        ),
    ]
