# Generated by Django 5.2.16 on 2026-08-08 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_url",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
