# Generated by Django 5.2.16 on 2026-08-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_target_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="target_link_text",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
