version: '2' # supported by default install on Ubuntu 18.04

services:
  db:
    container_name: db
    build: ./postgresql
    expose:
      - "5432"
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"  # http://support.divio.com/en/articles/3719228-database-is-uninitialized-and-superuser-password-is-not-specified
  redis:
    image: "redis:5.0-alpine" # Production server is using 3.0.6
    ports:
      - 6379:6379
  web:
    #restart: unless-stopped
    build: .
    env_file: .env
    command: bash -c "cd /app/src/ &&
                      python manage.py migrate_schemas --shared &&
                      python manage.py runserver 0.0.0.0:8000"
    volumes: 
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    links: 
      - db:db
    user: $UID:$GID
  celery:
    build: .
    env_file: .env
    command: bash -c "cd src &&
                      CELERY_RDBSIG=1 celery -A hackerspace_online worker -l info -c 3 -Q default"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
      - web
  celery-beat:
    build: .
    env_file: .env
    command: bash -c "cd src &&
                      CELERY_RDBSIG=1 celery -A hackerspace_online beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - .:/app
    depends_on:
      - db 
      - redis
      - web
volumes:
  postgres_data:
  redis_data:
