version: '2.2'

###############################################################################
#
# FOR DOCKER_COMPOSE SETTINGS SPECIFIC TO CI TESTS WITH GIT HUB WORKFLOWS
#
################################################################################

services:
  db:
    ports:
    - 5432:5432  # Expose port so app can connect to db when developing locally with `./src/manage.py [runserver|test src]
  redis:
    ports:
    - 6379:6379  # Expose port so app can connect to redis when developing locally with `./src/manage.py [runserver|test src]