# Generated by Django 2.0.9 on 2019-01-02 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cytoelement',
            name='data_parent',
            field=models.ForeignKey(blank=True, help_text='indicates the compound node parent; blank/null => no parent', limit_choices_to={'group': 'nodes'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='djcytoscape.CytoElement'),
        ),
        migrations.AlterField(
            model_name='cytoscape',
            name='initial_content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'quest_manager'), ('model', 'quest')), models.Q(('app_label', 'badges'), ('model', 'badge')), models.Q(('app_label', 'courses'), ('model', 'rank')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
