# Generated by Django 2.2.9 on 2020-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0002_auto_20190101_1713'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytoelement',
            name='selector_id',
            field=models.CharField(blank=True, help_text="unique id in the form of 'model-#' where the model = Quest (etc) and # = object id.", max_length=16, null=True),
        ),
    ]
