# Generated by Django 2.2.9 on 2020-03-31 20:57

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0003_cytoelement_selector_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytoelement',
            options={'ordering': ['-group', django.db.models.expressions.OrderBy(django.db.models.expressions.F('data_parent'), nulls_first=True)]},
        ),
    ]
