# Generated by Django 2.2.9 on 2020-04-03 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0004_auto_20200331_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytoscape',
            options={'verbose_name': 'Quest Map'},
        ),
        migrations.AlterModelOptions(
            name='cytostyleclass',
            options={'verbose_name': 'Map Style'},
        ),
        migrations.AlterModelOptions(
            name='cytostyleset',
            options={'verbose_name': 'Map Style Set'},
        ),
    ]
