# Generated by Django 2.2.13 on 2020-07-06 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0008_auto_20200705_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cytostyleset',
            name='style_classes',
        ),
        migrations.DeleteModel(
            name='CytoStyleClass',
        ),
        migrations.DeleteModel(
            name='CytoStyleSet',
        ),
    ]
