# Generated by Django 2.2.13 on 2020-07-06 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0010_remove_cytoscape_container_element_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytoscape',
            name='elements_json',
            field=models.TextField(blank=True, help_text='A cache of the json representing all elements in this scape.  Updated when the map is recalculated.', null=True),
        ),
    ]
