# Generated by Django 2.2.13 on 2020-07-22 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0011_cytoscape_elements_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='cytoelement',
            name='is_transition',
            field=models.BooleanField(default=False, help_text='Whether this node transitions to a new map'),
        ),
    ]
