# Generated by Django 3.2.17 on 2023-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djcytoscape', '0012_cytoelement_is_transition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cytoscape',
            options={'ordering': ['name'], 'verbose_name': 'Quest Map'},
        ),
    ]
