# Generated by Django 4.2.30 on 2026-07-18 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djcytoscape", "0014_alter_cytoelement_href"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cytoelement",
            options={
                "ordering": [
                    "-group",
                    models.OrderBy(models.F("data_parent"), nulls_first=True),
                    "id",
                ]
            },
        ),
    ]
