# Generated by Django 5.2.17 on 2026-08-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_question_import_id_3"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="allow_script_capable_files",
            field=models.BooleanField(
                default=False,
                help_text="Tick this only for a quest that asks for one: with <b>Image</b> or <b>Image or Video</b> it also accepts SVG, and with <b>All</b> it also accepts SVG, HTML, XML and similar. A browser can run a script from these, so such an answer is handed to you as a download rather than opened in ByteDeck. An SVG is shown as a picture as well, which browsers never run script in. Leave it unticked with <b>Video</b> or <b>Audio</b>: neither has such a file type.",
                verbose_name="Also allow file types that can carry a script",
            ),
        ),
    ]
