# Generated by Django 5.2.17 on 2026-08-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0004_question_import_id_3"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="allowed_file_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio"),
                    ("media", "Image or Video"),
                    ("all", "All"),
                    ("web", "Web files (HTML, CSS, JS, SVG)"),
                ],
                default="all",
                help_text="The types of files that can be uploaded by a student for this question. Choose <b>Web files</b> only for a quest that asks for a web page or an SVG: those are the file types a browser can run a script from, so an answer to such a question is handed to you as a download rather than opened in the site, and an SVG is shown as a picture (which browsers never run script in).",
                max_length=50,
            ),
        ),
    ]
