# Generated by Django 5.2.17 on 2026-09-30 17:18

import utilities.models
import utilities.uploads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("questions", "0005_question_allow_script_capable_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionsubmission",
            name="response_file",
            field=utilities.models.RestrictedFileField(
                blank=True,
                help_text="A file response to a question. This is what the teacher will look at when marking the question.",
                max_length=255,
                null=True,
                upload_to=utilities.uploads.UploadToOwnFolder(
                    "quest/question/submission/%Y/%m/%d"
                ),
            ),
        ),
    ]
