# Generated by Django 1.11.17 on 2018-12-28 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('content', models.TextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('datetime_last_edit', models.DateTimeField(auto_now=True)),
                ('sticky', models.BooleanField(default=False)),
                ('sticky_until', models.DateTimeField(blank=True, help_text='blank = sticky never expires', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='announcement_icons/')),
                ('datetime_released', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_expires', models.DateTimeField(blank=True, help_text='blank = never', null=True)),
                ('draft', models.BooleanField(default=True, help_text='note that announcements previously saved as drafts will only send out a                                  notification if they are published using the Publish button on the Announcements main                                 page')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
