# Generated by Django 2.0.13 on 2019-07-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='auto_publish',
            field=models.BooleanField(default=False, help_text='When set to true, the announcement will publish itself on the date and time indicated.'),
        ),
    ]
