# Generated by Django 2.0.13 on 2019-08-07 19:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_announcement_auto_publish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='datetime_released',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='The time the announcement was published.  If auto_publish is True, then the announcement will automatically         be published at this time.'),
        ),
    ]
