# Generated by Django 2.2.15 on 2020-09-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0003_auto_20190807_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
