# Generated by Django 2.2.13 on 2020-11-19 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0004_announcement_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='draft',
            field=models.BooleanField(default=True, help_text='A new announcement saved as a non-draft will be published and notifications sent.              Editing a previously saved draft will not send out notifications; use the Publish button on             the Announcements main page.'),
        ),
    ]
