#!/usr/bin/env bash
# Boot the production compose topology and assert how the containers can reach
# each other.
#
# This is the runtime half of the production checks; check_prod_compose.py is
# the static half. It exists because the regular test suite only ever runs the
# development overlay, so nothing else would notice a production-only
# regression such as the application port being published to the host.
#
# The application image is deliberately NOT used here. Substituting a trivial
# server for `web` keeps this about the topology (who can reach whom) and keeps
# it fast; the real image is covered by the Build and Test job.
set -euo pipefail

cd "$(dirname "$0")/../.."

DOMAIN_UNDER_TEST=topology-test.local
STAND_IN_IMAGE=python:3.12-slim
WORKDIR=$(mktemp -d)
CERT_DIR=$WORKDIR/letsencrypt/live/$DOMAIN_UNDER_TEST

# CDN_static is a required nginx build arg (the legacy /media/ redirect is
# rendered from it and the build fails on an empty value), so it gets a
# stand-in host here. Nothing in this file requests /media/, so the value only
# has to be non-empty and syntactically a host.
export ROOT_DOMAIN=$DOMAIN_UNDER_TEST WUID=0 WGID=0 CDN_static=cdn.$DOMAIN_UNDER_TEST
COMPOSE=(docker compose -p bytedeck-topotest
         -f docker-compose.yml
         -f docker-compose.prod.aws.yml
         -f "$WORKDIR/compose.topology-test.yml")

failures=0
check() {  # check <expected-to-succeed: yes|no> <description> <command...>
    local expectation=$1 description=$2
    shift 2
    if "$@" >/dev/null 2>&1; then result=yes; else result=no; fi
    if [ "$result" = "$expectation" ]; then
        echo "  PASS  $description"
    else
        echo "  FAIL  $description"
        failures=$((failures + 1))
    fi
}

cleanup() {
    "${COMPOSE[@]}" down -v --remove-orphans >/dev/null 2>&1 || true
    rm -rf "$WORKDIR"
}
trap cleanup EXIT

# Self-signed stand-ins for the certificates certbot manages on the real host.
# 2048 bits because nginx rejects a smaller dhparam outright.
mkdir -p "$CERT_DIR"
openssl req -x509 -newkey rsa:2048 -nodes -days 1 \
    -keyout "$CERT_DIR/privkey.pem" -out "$CERT_DIR/fullchain.pem" \
    -subj "/CN=$DOMAIN_UNDER_TEST" 2>/dev/null
openssl dhparam -out "$WORKDIR/letsencrypt/ssl-dhparams.pem" 2048 2>/dev/null

# The site config listens on both address families. On a host with IPv6
# compiled out, `listen [::]:8088` is a hard startup error, so nginx would never
# come up and every assertion below would fail for a reason that has nothing to
# do with the topology. Build from a copy without those lines instead, and say
# so, since the address family is not what this script is checking.
NGINX_CONTEXT=./nginx
if [ ! -d /proc/sys/net/ipv6 ]; then
    echo "NOTE: no IPv6 on this host, so nginx is built without its IPv6 listeners."
    NGINX_CONTEXT=$WORKDIR/nginx
    cp -r ./nginx "$NGINX_CONTEXT"
    sed -i '/listen \[::\]/d' "$NGINX_CONTEXT/bytedeck.conf.template"
fi

cat > "$WORKDIR/compose.topology-test.yml" <<EOF
# Generated by production/tests/check_prod_topology.sh. Replaces the app image
# with a trivial server and points nginx at throwaway certificates, so the
# production topology can be exercised without production secrets.
services:
  web:
    image: $STAND_IN_IMAGE
    command: python -m http.server 8000
  celery:
    image: $STAND_IN_IMAGE
    command: sleep infinity
    healthcheck: {test: ["CMD", "true"]}
  celery-beat:
    image: $STAND_IN_IMAGE
    command: sleep infinity
    healthcheck: {test: ["CMD", "true"]}
  nginx:
    build:
      context: $NGINX_CONTEXT
    volumes:
      - $WORKDIR/letsencrypt:/etc/letsencrypt
EOF

echo "Starting the production topology..."
docker pull -q "$STAND_IN_IMAGE" >/dev/null
# nginx is the one service genuinely built from this repo, so it is built here.
# Everything else runs from an existing image, which is what --no-build enforces
# below: the application image belongs to the Build and Test job, not this one.
"${COMPOSE[@]}" build nginx >/dev/null
"${COMPOSE[@]}" up -d --no-build --wait --wait-timeout 180 web redis nginx

echo
echo "Production topology assertions:"

# The application must not be reachable except through nginx, which is what
# terminates TLS and enforces the Host check.
check no "the host cannot reach web on :8000" \
    curl -sf --max-time 5 http://127.0.0.1:8000/
check yes "the host can reach nginx on :443" \
    curl -sk --max-time 10 -o /dev/null https://127.0.0.1/ -H "Host: $DOMAIN_UNDER_TEST"

# nginx proxies to web, so it must reach it; it has no business reaching redis.
check yes "nginx can reach web:8000" \
    "${COMPOSE[@]}" exec -T nginx bash -c 'timeout 3 bash -c "</dev/tcp/web/8000"'
check no "nginx cannot reach redis:6379" \
    "${COMPOSE[@]}" exec -T nginx bash -c 'timeout 3 bash -c "</dev/tcp/redis/6379"'
check yes "web can reach redis:6379" \
    "${COMPOSE[@]}" exec -T web python -c \
    "import socket; socket.create_connection(('redis', 6379), timeout=3).close()"

# A request for a domain this deck does not serve is dropped, not proxied.
check no "nginx drops a foreign Host header" \
    curl -sk --max-time 10 -o /dev/null https://127.0.0.1/ -H "Host: not-this-deck.example.com"

echo
if [ "$failures" -gt 0 ]; then
    echo "$failures failure(s)"
    "${COMPOSE[@]}" ps
    exit 1
fi
echo "0 failure(s)"
