# Generated by Django 1.11.17 on 2018-12-28 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import embed_video.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of this piece of art.', max_length=50)),
                ('description', models.TextField(blank=True, help_text='A description of the meaning of this art, how the art was made, or any other info you would like to share about this portfolio piece', null=True)),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='The date this art was created or completed')),
                ('image_file', models.ImageField(blank=True, help_text="OPTION 1. Your artwork or photograph to display. If a video file is also uploaded, this will be used as the video's preview image.", null=True, upload_to='portfolios/video/%Y/%m')),
                ('video_file', models.FileField(blank=True, help_text='OPTION 2. HTML5 Video types supported by all browsers are: MP4 (H.264 video +AAC or +MP3 audio) and WebM (VP8 video +Vorbis audio).You can upload other video types, but they may not play when you try to view your portfolio.', null=True, upload_to='portfolios/video/%Y/%m')),
                ('video_url', embed_video.fields.EmbedVideoField(blank=True, help_text='OPTION 3. You can also add YouTube or Vimeo videos to your Portfolio by providing the link here.  If a link is provided, the image and videofiles will be ignored.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('description', models.TextField(blank=True, help_text='A description to display with your portfolio', null=True)),
                ('listed_locally', models.BooleanField(default=False, help_text='Your portfolio will be listed on the Students page and other Hackerspace students will be able to see it.')),
                ('listed_publicly', models.BooleanField(default=False, help_text="Your portfolio will be listed publicly, for example on Timberline's website.")),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Portfolio'),
        ),
    ]
