# Generated by Django 2.2.12 on 2020-05-30 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20200529_1705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='listed_publicly',
            field=models.BooleanField(default=False, help_text='Your portfolio can be listed publicly by your teacher.'),
        ),
    ]
