#!/bin/bash

# if any of the commands in your code fails for any reason, the entire script fails
set -o errexit
# fail exit if one of your pipe command fails
set -o pipefail
# exits if any of your variables is not set
set -o nounset

cd /app/src/
python manage.py migrate_schemas --shared
python manage.py migrate_schemas --executor=multiprocessing
python manage.py collectstatic --noinput
uwsgi --ini uwsgi.aws.ini"