# Generated by Django 4.2.30 on 2026-07-13 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("contenttypes", "0002_remove_content_type_name"),
        ("quest_manager", "0048_alter_category_published"),
    ]

    operations = [
        migrations.CreateModel(
            name="Competency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="An optional elaboration or full text of this competency.",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text='A free-text strand or grouping, e.g. "Curricular Competency", "Big Idea", or "Core Competency".',
                        max_length=255,
                    ),
                ),
                (
                    "source_id",
                    models.CharField(
                        blank=True,
                        help_text="A stable identifier into a source taxonomy such as the BC curriculum. Used to de-duplicate imports and to match competencies across decks.",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True,
                        help_text="Instead of deleting a competency, deactivate it to hide it from new use while preserving existing assessment evidence. A competency that is referenced by assessment evidence cannot be deleted.",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "competencies",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="QuestCompetency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_level",
                    models.IntegerField(
                        choices=[
                            (1, "Emerging"),
                            (2, "Developing"),
                            (3, "Proficient"),
                            (4, "Extending"),
                        ],
                        default=3,
                        help_text="The proficiency level that completing this quest generally demonstrates. Teachers can adjust the level for individual students when approving submissions.",
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_competencies",
                        to="competencies.competency",
                    ),
                ),
                (
                    "quest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quest_competencies",
                        to="quest_manager.quest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "quest competencies",
            },
        ),
        migrations.CreateModel(
            name="CompetencyAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "level",
                    models.IntegerField(
                        choices=[
                            (1, "Emerging"),
                            (2, "Developing"),
                            (3, "Proficient"),
                            (4, "Extending"),
                        ]
                    ),
                ),
                (
                    "source_object_id",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("note", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The staff user who made this assessment. Null means self- or system-assessed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competency_assessments_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "competency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="competencies.competency",
                    ),
                ),
                (
                    "source_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="competency_assessments",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The student being assessed.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="competency_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.AddConstraint(
            model_name="questcompetency",
            constraint=models.UniqueConstraint(
                fields=("quest", "competency"), name="unique_quest_competency"
            ),
        ),
        migrations.AddIndex(
            model_name="competencyassessment",
            index=models.Index(
                fields=["user", "competency", "timestamp"],
                name="competency_evidence_idx",
            ),
        ),
    ]
