# Generated by Django 2.2.9 on 2020-04-02 05:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0010_course_xp_for_100_percent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='My Byte Deck', help_text="This name will appear throughout the site, for example: Timberline's Digital Hackerspace.", max_length=50, verbose_name='Site Name, Full')),
                ('site_name_short', models.CharField(default='Deck', help_text='Used when the full site name is too cumbersome, for example: Hackerspace.', max_length=20, verbose_name='Site Name, Short')),
                ('banner_image', models.ImageField(blank=True, help_text='The banner will be displayed on your landing page and in a smaller format at the top left of the site (ideally 1140px wide)', null=True, upload_to='', verbose_name='Banner Image')),
                ('banner_image_dark', models.ImageField(blank=True, help_text='An optional, alternate banner to be used with the dark theme.', null=True, upload_to='', verbose_name='Banner Image, Dark Theme')),
                ('site_logo', models.ImageField(blank=True, help_text='This becomes the default icon for quests and badges and other places where icons are used (ideally 256x256 px).', null=True, upload_to='', verbose_name='Site Logo')),
                ('favicon', models.ImageField(blank=True, help_text='The image used in browser tabs (ideally 16x16 px).', null=True, upload_to='', verbose_name='Favicon')),
                ('submission_quick_text', models.CharField(blank=True, default='Please read the submission instructions more carefully. Thanks! ', help_text='Quickly insert this text into your replies with a button.', max_length=255, verbose_name='Submission Quick Text')),
                ('blank_approval_text', models.CharField(blank=True, default='(Approved - Your submission meets the criteria for this quest)', help_text='This text will be inserted when you approve a quest without commenting.', max_length=255, verbose_name='Approved without Comment Text')),
                ('blank_return_text', models.CharField(blank=True, default='(Returned without comment)', help_text='This text will be inserted when you return a quest without commenting.', max_length=255, verbose_name='Returned without Comment Text')),
                ('color_headers_by_mark', models.BooleanField(blank=True, default=False, help_text='Set up at least one Mark Range in admin for this to do anything.', null=True, verbose_name='Activate Header Colors by Mark')),
                ('approve_oldest_first', models.BooleanField(blank=True, default=False, help_text='Check this if you want to have the quest that have been waiting the longed to appear on top of the list.', null=True, verbose_name='Sort quests awaiting approval with oldest on top')),
                ('hackerspace_ai', models.ForeignKey(default=1, help_text='This user will appear as granting automatic badges, sending out announcements, and other automated actions. Fun suggestion: create a new staff user named `R2-D2` or `Hal` or a similar AI name that fits the theme of your site.', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User for automated stuff')),
                ('hs_active_semester', models.ForeignKey(default=1, help_text='Your currently active semester.  New semesters can be created from the admin menu.', on_delete=django.db.models.deletion.SET_DEFAULT, to='courses.Semester', verbose_name='Active Semester')),
            ],
        ),
    ]
