# Generated by Django 2.2.9 on 2020-04-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='hs_active_semester',
            new_name='active_semester',
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='approve_oldest_first',
            field=models.BooleanField(default=False, help_text='Check this if you want to have the quest that have been waiting the longest to appear on top of the list.', verbose_name='Sort quests awaiting approval with oldest on top'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='color_headers_by_mark',
            field=models.BooleanField(default=False, help_text='Set up at least one Mark Range in admin for this to do anything.', verbose_name='Activate Header Colors by Mark'),
        ),
    ]
