# Generated by Django 2.2.9 on 2020-04-03 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siteconfig.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0002_auto_20200402_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='hackerspace_ai',
            field=models.ForeignKey(default=siteconfig.models.get_superadmin, help_text='This user will appear as granting automatic badges, sending out announcements, and other automated actions. Fun suggestion: create a new staff user named `R2-D2` or `Hal` or a similar AI name that fits the theme of your site.', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL, verbose_name='User for automated stuff'),
        ),
    ]
