# Generated by Django 2.2.9 on 2020-04-03 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0005_auto_20200403_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='The image used in browser tabs (ideally 16x16 px). It will fall back to your site logo if a seperate favicon is not provided.', null=True, upload_to='', verbose_name='Favicon'),
        ),
    ]
