# Generated by Django 2.2.12 on 2020-05-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0007_siteconfig_access_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='display_marks_calculation',
            field=models.BooleanField(default=False, help_text='Check this if you want to let students view their mark calculations.', verbose_name='Display marks calculation page'),
        ),
    ]
