# Generated by Django 2.2.12 on 2020-05-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0008_siteconfig_display_marks_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_icon',
            field=models.ImageField(blank=True, help_text='This becomes the default icon for quests and badges and other places where icons are used (ideally 64x64 px).If no icon is provided, it will fall back on the site logo (so you can leave this blank if you want to use your logo)', null=True, upload_to='', verbose_name='Default Icon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='favicon',
            field=models.ImageField(blank=True, help_text='The image used in browser tabs (ideally 32x32 px). It will fall back to your site logo if a seperate favicon is not provided.', null=True, upload_to='', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='site_logo',
            field=models.ImageField(blank=True, help_text="This will be displayed at the top left of your site's header (ideally 64x64 px).", null=True, upload_to='', verbose_name='Site Logo'),
        ),
    ]
