# Generated by Django 2.2.13 on 2020-06-23 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0010_auto_20200530_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='The image will be displayed at the top left of the site 262px wide', null=True, upload_to='', verbose_name='Banner Image'),
        ),
    ]
