# Generated by Django 2.2.16 on 2020-10-23 06:28

from django.db import migrations, models
import django.db.models.deletion
import siteconfig.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0011_auto_20200622_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='active_semester',
            field=models.ForeignKey(default=siteconfig.models.get_active_semester, help_text='Your currently active semester.  New semesters can be created from the admin menu.', on_delete=django.db.models.deletion.PROTECT, to='courses.Semester', verbose_name='Active Semester'),
        ),
    ]
