# Generated by Django 2.2.17 on 2021-02-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0012_auto_20201022_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='outgoing_email_signature',
            field=models.TextField(blank=True, help_text='Used when your deck sends your announcements and other notifications by email.', max_length=512, verbose_name='Outoging Email Signature'),
        ),
    ]
