# Generated by Django 3.2.12 on 2022-02-18 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0013_siteconfig_outgoing_email_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='cap_marks_at_100_percent',
            field=models.BooleanField(default=False, help_text='By default, if a student has more than the expected XP in their course             (for the amount of time that has passed in the semester so far) their mark will show greater than 100%.              Check this if you want to cap marks at 100%. This setting is only relevent if you are using mark percentages.', verbose_name='Cap marks at 100%'),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='display_marks_calculation',
            field=models.BooleanField(default=False, help_text='By default, the site only uses XP.  Check this if you also want to use percentages for student marks.             The conversion of XP to a percentage depends on several other settings in your deck.              <a href="https://github.com/bytedeck/bytedeck/wiki/Using-Mark-Percentages" target="_blank">See here</a> for a full explanation. ', verbose_name='Use mark percentages'),
        ),
    ]
