# Generated by Django 3.2.13 on 2022-06-15 23:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import siteconfig.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('siteconfig', '0014_auto_20220218_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='deck_owner',
            field=models.ForeignKey(default=siteconfig.models.get_default_deck_owner, help_text='Only the current deck owner can change this setting.', limit_choices_to={'is_staff': True}, on_delete=django.db.models.deletion.PROTECT, related_name='deck_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
