# Generated by Django 3.2.13 on 2022-08-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0015_siteconfig_deck_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_name_for_groups',
            field=models.CharField(default='Groups', help_text='A custom name specific to your deck to replace "Groups".  Groups can be used to assign a group of students             to a specific teacher, and/or used as a prerequisite. For example, "Blocks", "Cohorts", or "Sections"             might be a more suitable name than Groups, depending on your context.', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_name_for_tags',
            field=models.CharField(default='Tags', help_text='A custom name specific to your deck to replace "Tags".   For example, "Competencies", "Learning Outcomes",             or "Skills" might be a more suitable name, depending on how you use the Tags feature.', max_length=20),
        ),
    ]
