# Generated by Django 3.2.13 on 2022-08-12 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0016_auto_20220812_1045'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteconfig',
            old_name='custom_name_for_groups',
            new_name='custom_name_for_group'
        ),
        migrations.RenameField(
            model_name='siteconfig',
            old_name='custom_name_for_tags',
            new_name='custom_name_for_tag'
        ),

    ]
