# Generated by Django 3.2.13 on 2022-08-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0017_auto_20220812_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='custom_name_for_group',
            field=models.CharField(default='Group', help_text='A custom name specific to your deck to replace "Group".  Groups can be used to assign a group of students             to a specific teacher, and/or used as a prerequisite. For example, "Block", "Cohort", or "Section"             might be a more suitable name than Groups, depending on your context.', max_length=20),
        ),
        migrations.AlterField(
            model_name='siteconfig',
            name='custom_name_for_tag',
            field=models.CharField(default='Tag', help_text='A custom name specific to your deck to replace "Tag".   For example, "Competency", "Learning Outcome",             or "Skill" might be a more suitable name, depending on how you use the Tags feature.', max_length=20),
        ),
    ]
