# Generated by Django 3.2.18 on 2023-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0018_auto_20220812_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enable_google_signin',
            field=models.BooleanField(default=False, help_text="If you want to enable the ability to 'Sign in with Google' on your deck, please post a request <a href='https://github.com/bytedeck/bytedeck/discussions/1309' target='_blank'>here</a>", verbose_name='Enable sign-in via Google'),
        ),
    ]
