# Generated by Django 3.2.18 on 2023-03-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0018_auto_20220812_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enable_google_signin',
            field=models.BooleanField(default=False, verbose_name='Enable sign-in via Google'),
        ),
    ]
