# Generated by Django 3.2.17 on 2023-05-22 11:59

from django.db import migrations
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0019_siteconfig_enable_google_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_javascript',
            field=utilities.models.RestrictedFileField(blank=True, null=True, upload_to='', verbose_name='JavaScript'),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='custom_stylesheet',
            field=utilities.models.RestrictedFileField(blank=True, help_text='Upload a custom CSS file to customize the look of your site.', null=True, upload_to='', verbose_name='CSS'),
        ),
    ]
