# Generated by Django 3.2.17 on 2023-05-25 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0019_siteconfig_enable_google_signin'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_name_for_student',
            field=models.CharField(default='Student', help_text='A custom name specific to your deck to replace "Student". Students are non-staff site users, so this             setting should be changed to reflect the desired name for your deck\'s userbase. For example, "User", "Member"             or "Learner" might be a more suitable name than Student, depending on your context.', max_length=20),
        ),
    ]
