# Generated by Django 3.2.17 on 2023-05-27 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0020_auto_20230525_0432'),
        ('siteconfig', '0020_siteconfig_custom_name_for_student'),
    ]

    operations = [
    ]
