# Generated by Django 3.2.17 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0020_siteconfig_custom_name_for_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_name_for_announcement',
            field=models.CharField(default='Announcement', help_text='A custom name specific to your deck to replace "Announcement". Annoucements are site-wide messages created             by staff members and displayed to all users through a tab in the sidebar. Alternatives might include "Memo",             "Bulletin", or "Notice", depending on your context.', max_length=20),
        ),
    ]
