# Generated by Django 3.2.17 on 2023-05-31 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0022_auto_20230529_2010'),
        ('siteconfig', '0022_siteconfig_custom_name_for_badge'),
    ]

    operations = [
    ]
