# Generated by Django 3.2.18 on 2023-07-17 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0023_merge_20230530_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='simplified_course_registration',
            field=models.BooleanField(default=False, help_text='If this option is enabled, when a student registers for a course they will only have to select fields that have more than one             option. If your deck only has a single course, group, and semester, then the user will automatically be enrolled in the course without             having to submit a form.'),
        ),
    ]
