# Generated by Django 3.2.18 on 2023-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0024_siteconfig_simplified_course_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='banned_from_comments_text',
            field=models.CharField(default="You've been banned from commenting on announcements due to inappropriate conduct.", help_text='Whenever a student is banned from commenting on announcements, this text will be displayed in place of the usual comment form.', max_length=255, verbose_name='Banned from Announcement Comments Text'),
        ),
    ]
