# Generated by Django 3.2.18 on 2024-04-04 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0025_siteconfig_banned_from_comments_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='enable_shared_library',
            field=models.BooleanField(default=False, help_text='If enabled, you can import quests and campaigns from the Shared Library.', verbose_name='Enable Shared Library'),
        ),
    ]
