# Generated by Django 3.2.25 on 2024-05-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0026_add_enable_shared_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='show_all_tags_on_profiles',
            field=models.BooleanField(default=True, help_text='Controls the visibility of tags on user profiles. If set to False, only tags where the student has earned XP are displayed.'),
        ),
    ]
