# Generated by Django 3.2.25 on 2024-08-22 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0027_siteconfig_show_all_tags_on_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='custom_profile_field',
            field=models.CharField(blank=True, default='', help_text="This field can be used to collect custom data such as a student's grad year or other             important info you need from your users. If left blank this field will be ignored and will not appear on student profiles.", max_length=20),
        ),
    ]
