# Generated by Django 3.2.25 on 2024-07-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0027_siteconfig_show_all_tags_on_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='map_auto_update',
            field=models.BooleanField(default=True, help_text='Automatically regenerate maps when contents are changed.'),
        ),
    ]
