# Generated by Django 3.2.25 on 2024-08-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0028_siteconfig_custom_profile_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='map_auto_update',
            field=models.BooleanField(default=True, help_text='Automatically regenerate maps when contents are changed.'),
        ),
    ]
