# Generated by Django 4.2.21 on 2025-08-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0029_siteconfig_map_auto_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='allow_staff_export',
            field=models.BooleanField(default=False, help_text='If enabled, staff will be able to export quests and campaigns to the Shared Library;             otherwise only the owner can export quests.             See the <a href="https://github.com/bytedeck/bytedeck/wiki/Library#sharing-to-the-library" target="blank">help page</a> for details.', verbose_name='Allow staff to export quests to the library'),
        ),
    ]
