# Generated by Django 4.2.30 on 2026-07-13 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0030_siteconfig_allow_staff_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="competency_label_level_1",
            field=models.CharField(
                default="Emerging",
                help_text="The label displayed for the first (lowest) level of the proficiency scale.",
                max_length=50,
                verbose_name="Proficiency Scale Label, Level 1",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="competency_label_level_2",
            field=models.CharField(
                default="Developing",
                help_text="The label displayed for the second level of the proficiency scale.",
                max_length=50,
                verbose_name="Proficiency Scale Label, Level 2",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="competency_label_level_3",
            field=models.CharField(
                default="Proficient",
                help_text="The label displayed for the third level of the proficiency scale.             This is the default level demonstrated by completing a quest.",
                max_length=50,
                verbose_name="Proficiency Scale Label, Level 3",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="competency_label_level_4",
            field=models.CharField(
                default="Extending",
                help_text="The label displayed for the fourth (highest) level of the proficiency scale.",
                max_length=50,
                verbose_name="Proficiency Scale Label, Level 4",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="enable_competencies",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, you can attach competencies to quests and record proficiency-based             assessments (Emerging / Developing / Proficient / Extending) when approving submissions.",
                verbose_name="Enable Competencies",
            ),
        ),
    ]
