# Generated by Django 5.2.16 on 2026-07-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0030_siteconfig_allow_staff_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="enable_submission_questions",
            field=models.BooleanField(
                default=False,
                help_text="If enabled, staff can add questions (short answer, long answer, or file upload) to a quest,             which students answer as part of submitting that quest.",
                verbose_name="Enable Submission Questions",
            ),
        ),
    ]
