# Generated by Django 5.2.16 on 2026-07-23 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0031_siteconfig_enable_submission_questions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="enable_submission_questions",
        ),
    ]
