# Generated by Django 5.2.16 on 2026-08-16 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0033_alter_siteconfig_active_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="students_choose_xp_course",
            field=models.BooleanField(
                default=True,
                help_text="When a student in more than one course hands in a quest, they say which course it counts toward. Turn this off to share every             student's XP evenly between their courses instead. Students in a single course are never asked either way, and work handed in before             this was turned on stays evenly shared.",
                verbose_name="Students choose which course their XP counts toward",
            ),
        ),
    ]
