# Generated by Django 5.2.17 on 2026-10-03 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0018_normalize_badge_fa_icon_names"),
        ("siteconfig", "0034_siteconfig_students_choose_xp_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="default_quest_prerequisite",
            field=models.ForeignKey(
                blank=True,
                help_text="A badge to fill in as the prerequisite of each quest you create, under its Basic Prerequisites, where you can change or remove it. Without one, a new quest you forget to give a prerequisite is available to every student as soon as it's published.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="badges.badge",
                verbose_name="Default quest prerequisite",
            ),
        ),
    ]
