# Generated by Django 5.2.17 on 2026-09-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0034_siteconfig_students_choose_xp_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="submission_comments_oldest_first",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Check this if you want a submission's comments listed in the order they were written, so the thread reads from the first hand-in down to the latest reply. By default the newest comment is on top.",
                verbose_name="Sort the comments on a submission with oldest on top",
            ),
        ),
    ]
