# Generated by Django 5.2.17 on 2026-10-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0034_siteconfig_students_choose_xp_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="tickable_lists",
            field=models.BooleanField(
                db_default=False,
                default=False,
                help_text="Check this to put a tick box on each item of every bulleted and numbered list in a quest's Quest Details and Submission Instructions, so students can tick off the steps as they go. The ticks aren't saved. Without this, only lists given the class \"tickable\" get tick boxes.",
                verbose_name="Tick boxes on every list in a quest",
            ),
        ),
    ]
