# Generated by Django 5.2.17 on 2026-10-08 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("siteconfig", "0036_set_default_quest_prerequisite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="allow_staff_export",
            field=models.BooleanField(
                default=False,
                help_text='If enabled, staff will be able to export quests and campaigns to the Shared Library; otherwise only the owner can export quests. See the <a href="https://bytedeck.github.io/bytedeck/quests/shared-library/#share-to-the-library" target="_blank">User Guide</a> for details.',
                verbose_name="Allow staff to export quests to the library",
            ),
        ),
    ]
