# Generated by Django 2.0.9 on 2019-01-02 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='specific_teacher_to_notify',
            field=models.ForeignKey(blank=True, help_text='Notifications related to this quest will be sent to this teacher even if they do not teach the student.', limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
