# Generated by Django 2.0.13 on 2019-03-12 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0003_auto_20190111_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='import_id',
            field=models.UUIDField(default=uuid.uuid4,
                                   help_text='Only edit this if you want to link to a quest in another system so that when importing from that other system, it will update this quest. Otherwise do not edit this or it will break existing links!',
                                   null=True),
        ),
    ]
