# Generated by Django 2.0.13 on 2019-03-12 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0003_auto_20190111_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='import_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
