# Generated by Django 2.0.13 on 2019-03-12 21:59
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model('quest_manager', 'Quest')
    for row in MyModel.objects.all():
        row.import_id = uuid.uuid4()
        row.save(update_fields=['import_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0004_quest_import_id'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
