# Generated by Django 2.0.13 on 2019-08-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0007_auto_20190327_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='questsubmission',
            name='is_draft',
            field=models.BooleanField(default=True),
        ),
    ]
