# Generated by Django 2.0.13 on 2019-08-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0008_questsubmission_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questsubmission',
            name='is_draft',
        ),
        migrations.AddField(
            model_name='questsubmission',
            name='draft_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
