# Generated by Django 2.2.9 on 2020-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0010_auto_20200104_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='blocking',
            field=models.BooleanField(default=False, help_text='When this quest becomes available, it will block all other non-blocking quests until this it is completed'),
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
