# Generated by Django 2.2.9 on 2020-01-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0011_auto_20200105_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='repeat_per_semester',
            field=models.BooleanField(default=False, help_text='Use max_repeats as a semester limit, rather than as a global limit.'),
        ),
    ]
