# Generated by Django 2.2.9 on 2020-02-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0012_quest_repeat_per_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='repeat_per_semester',
            field=models.BooleanField(default=False, help_text='Repeatable once per semester, and Max Repeats becomes additional repeats per semester'),
        ),
    ]
