# Generated by Django 2.2.9 on 2020-04-07 15:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0013_auto_20200211_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='date_available',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
