# Generated by Django 2.2.12 on 2020-05-10 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0014_auto_20200407_0814'),
    ]

    operations = [
        # migrations.RunPython(load_initial_data),
    ]
