# Generated by Django 2.2.12 on 2020-05-10 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0015_campaign_and_quest_initial_data'),
        ('prerequisites', '0004_auto_20190702_0311'),
        ('badges', '0009_badge_initialdata')
    ]

    operations = [
        # migrations.RunPython(load_orientation_campaign),
    ]
