# Generated by Django 2.2.13 on 2020-08-15 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0016_orientation_campaign_initial_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='archived',
            field=models.BooleanField(default=False, help_text='Setting this will prevent it from appearing in admin quest lists.  To un-archive a quest, you will need to access it through Site Administration.'),
        ),
    ]
