# Generated by Django 2.2.13 on 2021-02-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0018_auto_20200818_1356_squashed_0019_auto_20200818_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='blocking',
            field=models.BooleanField(default=False, help_text='When this quest becomes available, it will block all other non-blocking quests until this one is submitted.'),
        ),
    ]
