# Generated by Django 2.2.24 on 2021-11-18 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0020_quest_max_xp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='max_xp',
            field=models.IntegerField(default=-1, help_text="The maximum amount of XP that can be gain by repeating this quest. If the Max Repeats hasn't been hit yet         then quest will continue to appear after this number is reached, but students will no longer         gain XP for completing it; -1 = unlimited"),
        ),
    ]
