# Generated by Django 2.2.24 on 2022-01-16 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0023_auto_20211124_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='map_transition',
            field=models.BooleanField(default=False, help_text='Break maps at this quest. This quest will link to a new map.'),
        ),
    ]
