# Generated by Django 2.2.24 on 2022-01-30 06:59

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0004_alter_taggeditem_content_type_alter_taggeditem_tag'),
        ('quest_manager', '0024_quest_map_transition'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
