# Generated by Django 3.2.13 on 2022-07-03 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0026_alter_quest_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={},
        ),
    ]
