# Generated by Django 3.2.13 on 2022-08-15 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0028_alter_quest_visible_to_students'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='active',
            field=models.BooleanField(default=True, help_text="Quests that are a part of an inactive campaign won't appear on quest maps and won't be available to students."),
        ),
    ]
