# Generated by Django 3.2.14 on 2022-07-22 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0028_rename_commondata_commonquestinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='common_data',
            new_name='common_quest_info',
        ),
    ]
