# Generated by Django 3.2.13 on 2022-08-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0029_alter_category_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='visible_to_students',
            field=models.BooleanField(default=True, help_text='If not checked, this quest will not be visible to students and will appear in your Drafts tab.', verbose_name='published'),
        ),
    ]
