# Generated by Django 3.2.16 on 2022-12-03 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0030_alter_quest_visible_to_students'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['sort_order', '-time_expired', '-date_expired', 'name']},
        ),
    ]
