# Generated by Django 3.2.18 on 2023-04-09 02:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0031_alter_quest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='date_available',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
