# Generated by Django 3.2.16 on 2022-12-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0031_alter_quest_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questsubmission',
            constraint=models.UniqueConstraint(fields=('quest', 'user', 'ordinal', 'semester'), name='unique_quest_submission'),
        ),
    ]
