# Generated by Django 3.2.18 on 2023-09-03 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211130_2003'),
        ('quest_manager', '0032_alter_quest_date_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='questsubmission',
            name='draft_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment'),
        ),
    ]
