# Generated by Django 3.2.18 on 2023-11-11 06:12

from django.db import migrations
from django.db import connection



def delete_orphaned_quest_submissions(apps, schema_editor):
    from django_tenants.utils import get_public_schema_name

    if connection.schema_name == get_public_schema_name():
        return

    QuestSubmission = apps.get_model('quest_manager', 'QuestSubmission')

    quest_submissions = QuestSubmission.objects.filter(quest__isnull=True)
    quest_submissions.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0032_alter_quest_date_available'),
    ]

    operations = [
        migrations.RunPython(delete_orphaned_quest_submissions, reverse_code=migrations.RunPython.noop)
    ]

