# Generated by Django 3.2.18 on 2023-11-11 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0033_delete_orphaned_quest_submissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quest_manager.quest'),
        ),
    ]
