# Generated by Django 3.2.25 on 2024-07-22 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0035_questsubmission_draft_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quest',
            options={'ordering': ['sort_order', 'date_expired', 'time_expired', 'name']},
        ),
    ]
