# Generated by Django 3.2.25 on 2024-08-08 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211130_2003'),
        ('quest_manager', '0036_alter_quest_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questsubmission',
            name='draft_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='comments.comment'),
        ),
    ]
