# Generated by Django 4.2.21 on 2025-05-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0038_remove_questsubmission_draft_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='short_description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
