# Generated by Django 4.2.21 on 2025-05-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0038_remove_questsubmission_draft_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='questsubmission',
            name='time_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
