# Generated by Django 4.2.21 on 2025-06-21 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0039_category_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='archived',
            field=models.BooleanField(default=False, help_text='Move this quest into the archived tab.'),
        ),
    ]
