# Generated by Django 4.2.21 on 2025-06-05 19:16

from django.db import migrations, models
import uuid


def backfill_category_import_ids(apps, schema_editor):
    Category = apps.get_model('quest_manager', 'Category')
    for category in Category.objects.filter(import_id__isnull=True):
        category.import_id = uuid.uuid4()
        category.save(update_fields=["import_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0039_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='import_id',
            field=models.UUIDField(
                blank=True,
                null=True,
                help_text="Used to link this object across schemas. Don't edit manually unless necessary.",
            ),
        ),
        migrations.RunPython(backfill_category_import_ids, reverse_code=migrations.RunPython.noop),
    ]
