# Generated by Django 4.2.21 on 2025-06-05 19:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0039_category_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='import_id',
            field=models.UUIDField(blank=True, default=uuid.uuid4, help_text="Used to link this object across schemas. Don't edit manually unless necessary.", null=True, unique=True),
        ),
    ]
