# Generated by Django 4.2.21 on 2025-06-28 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    replaces = [('quest_manager', '0041_alter_category_import_id'), ('quest_manager', '0042_alter_category_import_id')]

    dependencies = [
        ('quest_manager', '0040_category_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='import_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="Used to link this object across schemas. Don't edit manually unless necessary.", unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='import_id',
            field=models.UUIDField(default=uuid.uuid4, help_text='This value links your campaign to the corresponding campaign within the Library. Only change this value if you want to disconnect your campaign from the Library.', unique=True),
        ),
    ]
