# Generated by Django 4.2.21 on 2025-06-26 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0040_category_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='import_id',
            field=models.UUIDField(default=uuid.uuid4, help_text="Used to link this object across schemas. Don't edit manually unless necessary.", unique=True),
        ),
    ]
