# Generated by Django 4.2.21 on 2025-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0041_alter_category_import_id_squashed_0042_alter_category_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='archived',
            field=models.BooleanField(default=False, help_text='Move this quest into the archived tab.'),
        ),
    ]
