# Generated by Django 4.2.21 on 2025-07-06 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0040_category_import_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='archived',
            field=models.BooleanField(default=False, help_text='Move this quest into the Archived tab.'),
        ),
    ]
