# Generated by Django 4.2.21 on 2025-07-06 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0041_alter_category_import_id_squashed_0042_alter_category_import_id'),
        ('quest_manager', '0043_alter_quest_archived'),
    ]

    operations = [
    ]
