# Generated by Django 4.2.21 on 2025-07-18 19:42

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0044_merge_20250706_1213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quest',
            old_name='visible_to_students',
            new_name='published',
        ),
    ]
