# Generated by Django 4.2.21 on 2025-07-18 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0045_rename_visible_to_students_to_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quest',
            name='published',
            field=models.BooleanField(default=True, help_text='If not checked, this quest will not be published and will appear in your Drafts tab.'),
        ),
    ]
