# Generated by Django 4.2.21 on 2025-07-26 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0046_alter_quest_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='active',
            new_name='published',
        ),
    ]