# Generated by Django 4.2.21 on 2025-07-27 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quest_manager', '0047_rename_category_active_to_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='published',
            field=models.BooleanField(default=True, help_text="Quests that are a part of an unpublished campaign won't appear on quest maps and won't be available to students."),
        ),
    ]
