# Generated by Django 4.2.30 on 2026-07-15 14:08

from django.db import migrations, models

# Delete duplicates in bounded batches so a deck with a pathological number of
# duplicate rows can't produce an unbounded pk__in list in a single query.
DEDUP_BATCH_SIZE = 500


def remove_duplicate_in_progress_submissions(apps, schema_editor):
    """Delete duplicate *never-yet-completed* in-progress submissions before
    adding the unique constraint (issue #1345).

    A concurrent "double start" could historically create more than one
    in-progress (``is_completed=False``, never completed) submission for the
    same ``(user, quest, semester)``. Those rows would violate the new partial
    unique constraint, so keep the earliest (lowest pk) of each group and
    delete the rest.

    Untouched (they can't violate the partial index):
    - completed submissions;
    - *returned* submissions (``is_completed=False`` but ``first_time_completed``
      set) -- a teacher returning an old submission of a repeatable quest while
      a new one is in progress is a legitimate state;
    - rows with a NULL semester (the index treats NULLs as distinct).
    """
    QuestSubmission = apps.get_model("quest_manager", "QuestSubmission")
    db_alias = schema_editor.connection.alias

    # ``seen`` is bounded by the number of *distinct* never-completed
    # in-progress (user, quest, semester) groups, which is small in practice;
    # deletes are flushed in DEDUP_BATCH_SIZE chunks so no single query gets an
    # unbounded pk__in list.
    seen = set()
    duplicate_pks = []
    in_progress = (
        QuestSubmission.objects.using(db_alias)
        .filter(is_completed=False, first_time_completed__isnull=True)
        .order_by("pk")
        .values_list("pk", "user_id", "quest_id", "semester_id")
    )
    for pk, user_id, quest_id, semester_id in in_progress.iterator():
        if semester_id is None:
            continue
        key = (user_id, quest_id, semester_id)
        if key in seen:
            duplicate_pks.append(pk)
            if len(duplicate_pks) >= DEDUP_BATCH_SIZE:
                QuestSubmission.objects.using(db_alias).filter(pk__in=duplicate_pks).delete()
                duplicate_pks = []
        else:
            seen.add(key)

    if duplicate_pks:
        QuestSubmission.objects.using(db_alias).filter(pk__in=duplicate_pks).delete()


class Migration(migrations.Migration):
    """Add the partial unique constraint that blocks concurrent double-starts
    (issue #1345), first deduplicating any historical conflicting in-progress
    rows so the constraint can be installed on existing decks."""

    dependencies = [
        ("quest_manager", "0048_alter_category_published"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_in_progress_submissions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="questsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_completed", False), ("first_time_completed__isnull", True)),
                fields=("user", "quest", "semester"),
                name="unique_inprogress_submission_per_quest_semester",
            ),
        ),
    ]
