# Generated by Django 4.2.30 on 2026-07-15 14:08

from django.db import migrations, models


def remove_duplicate_in_progress_submissions(apps, schema_editor):
    """Delete duplicate *in-progress* submissions before adding the unique
    constraint (issue #1345).

    A concurrent "double start" could historically create more than one
    in-progress (``is_completed=False``) submission for the same
    ``(user, quest, semester)``. Those rows would violate the new partial
    unique constraint, so keep the earliest (lowest pk) of each group and
    delete the rest. Completed submissions are untouched, and rows with a
    NULL semester are skipped (the partial index treats NULLs as distinct, so
    they can't violate the constraint anyway).
    """
    QuestSubmission = apps.get_model("quest_manager", "QuestSubmission")
    db_alias = schema_editor.connection.alias

    seen = set()
    duplicate_pks = []
    in_progress = (
        QuestSubmission.objects.using(db_alias)
        .filter(is_completed=False)
        .order_by("pk")
        .values_list("pk", "user_id", "quest_id", "semester_id")
    )
    for pk, user_id, quest_id, semester_id in in_progress.iterator():
        if semester_id is None:
            continue
        key = (user_id, quest_id, semester_id)
        if key in seen:
            duplicate_pks.append(pk)
        else:
            seen.add(key)

    if duplicate_pks:
        QuestSubmission.objects.using(db_alias).filter(pk__in=duplicate_pks).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("quest_manager", "0048_alter_category_published"),
    ]

    operations = [
        migrations.RunPython(
            remove_duplicate_in_progress_submissions,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name="questsubmission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_completed", False)),
                fields=("user", "quest", "semester"),
                name="unique_inprogress_submission_per_quest_semester",
            ),
        ),
    ]
