# Generated by Django 4.2.30 on 2026-07-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_manager", "0049_inprogress_submission_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="map_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Controls where this campaign sits, left to right, on quest maps: campaigns with a lower number are placed further to the left. Campaigns sharing a number (including the default 0) keep their creation order. Exact placement is still up to the map's layout engine, so this is a preference rather than a guarantee when campaigns are tangled together by prerequisites.",
            ),
        ),
    ]
