# Generated by Django 5.2.16 on 2026-07-23 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_manager", "0050_category_map_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="quest",
            name="quick_reply",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Quest-specific text (e.g. a reminder for a common mistake) that you can insert into a reply with one button when approving or returning submissions of this quest.",
                max_length=255,
                verbose_name="Quick Reply Text",
            ),
        ),
    ]
