# Generated by Django 5.2.16 on 2026-08-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_semester_status"),
        ("quest_manager", "0051_quest_quick_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questsubmission",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.semester",
            ),
        ),
    ]
