# Generated by Django 5.2.16 on 2026-07-22 07:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0028_semester_name"),
        ("quest_manager", "0051_redorequest"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="redorequest",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_approved", False), ("is_denied", False)),
                fields=("user", "quest"),
                name="unique_pending_redo_request_per_user_quest",
            ),
        ),
    ]
