# Generated by Django 5.2.16 on 2026-08-16 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0029_semester_status"),
        ("quest_manager", "0052_alter_questsubmission_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="questsubmission",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="The course this submission's XP counts toward.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
    ]
