# Generated by Django 5.2.17 on 2026-09-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quest_manager", "0054_inprogress_submission_no_semester_constraint"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="map_order",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Not currently used. Quest map layout is decided by the map's layout engine.",
            ),
        ),
    ]
