# Generated by Django 1.11.17 on 2018-12-28 03:51

from django.db import migrations, models
import django.db.models.deletion
import prerequisites.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prereq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Providing a name to a prereq allows it to be used itself as a prerequisite. One use for this to to chain more than two OR conditions.', max_length=256, null=True)),
                ('parent_object_id', models.PositiveIntegerField()),
                ('prereq_object_id', models.PositiveIntegerField(verbose_name='Prerequisite')),
                ('prereq_count', models.PositiveIntegerField(default=1)),
                ('prereq_invert', models.BooleanField(default=False, verbose_name='NOT')),
                ('or_prereq_object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='OR Prerequisite')),
                ('or_prereq_count', models.PositiveIntegerField(default=1)),
                ('or_prereq_invert', models.BooleanField(default=False, verbose_name='OR NOT')),
                ('or_prereq_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_prereq_item', to='contenttypes.ContentType', verbose_name='OR Type of Prerequisite')),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_parent', to='contenttypes.ContentType')),
                ('prereq_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prereq_item', to='contenttypes.ContentType', verbose_name='Type of Prerequisite')),
            ],
            bases=(models.Model, prerequisites.models.IsAPrereqMixin),
        ),
    ]
