# Generated by Django 2.0.13 on 2019-06-11 23:04
import djconfig
from django.db import migrations

from prerequisites.tasks import update_quest_conditions_all



def forwards(apps, schema_editor):
    # These don't work if db is empty 
    #djconfig.reload_maybe()
    #update_quest_conditions_all.apply_async(args=[1], queue='default')
    pass

def backwards(apps, schema_editor):
    PrereqAllConditionsMet = apps.get_model("prerequisites", "PrereqAllConditionsMet")
    PrereqAllConditionsMet.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0002_prereqallconditionsmet'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
