# Generated by Django 2.0.13 on 2019-07-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0003_upd_quest_conditions_met'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereqallconditionsmet',
            name='ids',
            field=models.TextField(),
        ),
    ]
