# Generated by Django 2.2.13 on 2020-07-06 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prerequisites', '0004_auto_20190702_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereqallconditionsmet',
            name='ids',
            field=models.TextField(default='[]'),
        ),
    ]
