# Generated by Django 3.2.13 on 2022-06-30 01:07

from django.db import migrations, models
import django.db.models.deletion
import prerequisites.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('prerequisites', '0005_auto_20200705_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prereq',
            name='or_prereq_content_type',
            field=models.ForeignKey(blank=True, limit_choices_to=prerequisites.models.Prereq.limit_prereq_choices, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='or_prereq_item', to='contenttypes.contenttype', verbose_name='OR Type of Prerequisite'),
        ),
        migrations.AlterField(
            model_name='prereq',
            name='or_prereq_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Alternate prereq object count'),
        ),
        migrations.AlterField(
            model_name='prereq',
            name='or_prereq_invert',
            field=models.BooleanField(default=False, verbose_name='NOT alternate prereq object'),
        ),
        migrations.AlterField(
            model_name='prereq',
            name='prereq_content_type',
            field=models.ForeignKey(limit_choices_to=prerequisites.models.Prereq.limit_prereq_choices, on_delete=django.db.models.deletion.CASCADE, related_name='prereq_item', to='contenttypes.contenttype', verbose_name='Type of Prerequisite'),
        ),
        migrations.AlterField(
            model_name='prereq',
            name='prereq_count',
            field=models.PositiveIntegerField(default=1, help_text="The number of times the 'prereq object' must be met before this prerequisite is considered complete. This value will only be meaningful for certain kinds of prereq objects such as repeatable quests, or badges."),
        ),
        migrations.AlterField(
            model_name='prereq',
            name='prereq_invert',
            field=models.BooleanField(default=False, help_text='This prerequisite is considered complete if they do NOT meet the criteria.', verbose_name='NOT'),
        ),
    ]
