# Generated by Django 4.2.30 on 2026-07-13 20:56

from django.db import migrations, models
from django.db.models import Count


def delete_duplicate_condition_caches(apps, schema_editor):
    """Delete duplicate PrereqAllConditionsMet objects (issue #520), keeping only the
    most recent (highest pk) object per (user, model_name).  Duplicates were created
    by concurrently running celery tasks, and any deleted cache will simply be
    recalculated by the next conditions-update task.
    """
    PrereqAllConditionsMet = apps.get_model('prerequisites', 'PrereqAllConditionsMet')

    duplicate_groups = (
        PrereqAllConditionsMet.objects
        .values('user', 'model_name')
        .annotate(count=Count('id'))
        .filter(count__gt=1)
    )
    for group in duplicate_groups:
        caches = PrereqAllConditionsMet.objects.filter(
            user=group['user'], model_name=group['model_name']
        ).order_by('-pk')
        # keep the first (highest pk), delete the rest
        PrereqAllConditionsMet.objects.filter(
            pk__in=[cache.pk for cache in caches[1:]]
        ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("prerequisites", "0006_auto_20220629_1807"),
    ]

    operations = [
        migrations.RunPython(delete_duplicate_condition_caches, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="prereqallconditionsmet",
            constraint=models.UniqueConstraint(
                fields=("user", "model_name"), name="unique_user_model_name"
            ),
        ),
    ]
