# Generated by Django 2.2.11 on 2020-03-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
