# Generated by Django 2.2.12 on 2020-04-05 13:47

from django.db import migrations, models
import tenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0002_tenant_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=100, unique=True, validators=[tenant.models.check_tenant_name]),
        ),
    ]
