# Generated by Django 2.2.13 on 2020-08-13 23:29

from django.db import migrations, models
import tenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20200522_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(help_text='The name of your deck, for example the name `example` would give you the site: `example.bytedeck.com` \n        The name may only include lowercase letters, numbers, and dashes.         It must start with a letter, and may not end in a dash nor include consecutive dashes', max_length=62, unique=True, validators=[tenant.models.check_tenant_name]),
        ),
    ]
