# Generated by Django 2.2.14 on 2020-07-29 17:10

from django.db import migrations, models
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0004_auto_20200522_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='domain_url',
        ),
        migrations.AlterField(
            model_name='tenant',
            name='schema_name',
            field=models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name]),
        ),
    ]
