# Generated by Django 2.2.16 on 2020-10-08 04:56

from django.conf import settings
from django.db import migrations

from django_tenants.utils import get_public_schema_name


def create_tenant_domain(apps, schema_editor):
    Tenant = apps.get_model('tenant', 'Tenant')

    for tenant in Tenant.objects.all():

        if tenant.domains.exists():
            continue

        if tenant.schema_name == get_public_schema_name():
            domain = settings.ROOT_DOMAIN
        else:
            domain = f'{tenant.name.lower()}.{settings.ROOT_DOMAIN}'

        tenant.domains.create(domain=domain, is_primary=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0006_auto_20201007_2154'),
    ]

    operations = [
        migrations.RunPython(create_tenant_domain)
    ]
