# Generated by Django 3.2.13 on 2022-08-10 02:59

from django.db import migrations, models
import tenant.models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0008_populate_tenant_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='max_active_users',
            field=models.SmallIntegerField(default=5, help_text='The maximum number of users that can be active on this deck; -1 = unlimited.'),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='trial_end_date',
            field=models.DateField(default=tenant.models.default_trial_end_date, help_text='The date when the trial period ends. Blank or a date in the past means the deck is not in trial mode.', null=True),
        ),
    ]
