# Generated by Django 3.2.13 on 2022-08-14 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0009_auto_20220809_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='active_user_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='This is a cached field: the number of staff users, plus the number student users currently             registered in a course in an active semester.'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='last_staff_login',
            field=models.DateTimeField(blank=True, help_text='This is a cached field: the last time a staff user logged in to the deck.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='quest_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='This is a cached field: the number of non-archived quests in the deck'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='total_user_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='This is a cached field: all users, including currently unregistered and archived users.'),
        ),
    ]
