# Generated by Django 3.2.17 on 2023-06-04 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0010_auto_20220814_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='google_signon_enabled',
            field=models.BooleanField(default=False, help_text='This is a cached field: Whether Google signon has been enabled for this deck.'),
        ),
    ]
