# Generated by Django 3.2.18 on 2023-08-13 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0011_tenant_google_signon_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, help_text='DEPRECATED: Primary e-mail address.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_full_name',
            field=models.CharField(blank=True, help_text='DEPRECATED: The owner of this deck.', max_length=255, null=True),
        ),
    ]
