# Generated by Django 3.2.18 on 2023-08-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0012_auto_20230812_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='owner_email',
            field=models.EmailField(blank=True, help_text="DEPRECATED: the verified email address of the Deck Owner (set in each deck's Site Config) will be used.         This field will be removed in a future update", max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='owner_full_name',
            field=models.CharField(blank=True, help_text="DEPRECATED: the full name of the Deck Owner (set in each deck's Site Config) will be used.         This field will be removed in a future update", max_length=255, null=True),
        ),
    ]
