# Generated by Django 3.2.18 on 2023-11-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0013_auto_20230825_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='owner_email_cached',
            field=models.EmailField(blank=True, editable=False, help_text="This is a cached field: the verified email address of the Deck Owner (set in each deck's Site Config) will be used.", max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='owner_full_name_cached',
            field=models.CharField(blank=True, editable=False, help_text="This is a cached field: the full name of the Deck Owner (set in each deck's Site Config) will be used.", max_length=255, null=True),
        ),
    ]
