# Generated by Django 4.2.16 on 2025-03-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0014_auto_20231116_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, editable=False, help_text='This is the stripe customer id for the deck owner.', null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, editable=False, help_text='This is the stripe subscription id for the deck owner.', null=True),
        ),
    ]
