# Generated by Django 5.2.16 on 2026-07-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0015_ensure_allauth_account_tables"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="active_user_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="This is a cached field: the number of student users currently registered in a course             in the active semester. Staff and superusers don't count.",
            ),
        ),
    ]
