# Generated by Django 5.2.16 on 2026-07-21 19:11

import tenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0016_alter_tenant_active_user_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="trial_end_date",
            field=models.DateField(
                blank=True,
                default=tenant.models.default_trial_end_date,
                help_text="The date when the trial period ends. Blank or a date in the past means the deck is not in trial mode.",
                null=True,
            ),
        ),
    ]
