# Generated by Django 5.2.16 on 2026-07-22 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0017_alter_tenant_trial_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="cached_fields_updated_on",
            field=models.DateTimeField(
                blank=True,
                editable=False,
                help_text="When the cached fields above were last refreshed (nightly via the deck status check task).",
                null=True,
            ),
        ),
    ]
