# Generated by Django 5.2.16 on 2026-07-22 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0018_tenant_cached_fields_updated_on"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="active_user_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="This is a cached field: the number of CURRENT students (registered in a course in the             active semester). Staff and superusers don't count.",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="max_active_users",
            field=models.SmallIntegerField(
                default=5,
                help_text="The maximum number of CURRENT students (registered in a course in the active semester)             on this deck; -1 = unlimited. Staff and merely-active (unregistered) students don't count.",
            ),
        ),
    ]
