# Generated by Django 5.2.16 on 2026-07-22 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0019_alter_tenant_active_user_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeckNotice",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("expiry", "Trial/subscription expiry reminder"),
                            ("limit", "Current-student limit warning"),
                            ("suspended", "Deck suspended"),
                            ("payment_failed", "Payment failed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "threshold",
                    models.CharField(
                        help_text="Which step of the cadence fired: 'd30'/'d14'/'d7', 'daily-YYYY-MM-DD', 'pct80'/'pct100', or 'suspended'.",
                        max_length=20,
                    ),
                ),
                (
                    "period_key",
                    models.CharField(
                        help_text="The deadline (expiry/suspension) or month (limit warnings) this notice was about;             a new value re-arms the threshold.",
                        max_length=32,
                    ),
                ),
                ("sent_on", models.DateField(auto_now_add=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="tenant.tenant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("tenant", "kind", "threshold", "period_key"),
                        name="unique_deck_notice",
                    )
                ],
            },
        ),
    ]
