# Generated by Django 5.2.16 on 2026-07-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0020_decknotice"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The Stripe Customer id (cus_...) this deck bills to. Blank = not linked to Stripe.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Stripe Subscription id (sub_...) paying for this deck. Blank = no Stripe subscription.",
                max_length=255,
            ),
        ),
    ]
