# Generated by Django 5.2.16 on 2026-07-24 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0021_tenant_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="can_delete",
            field=models.BooleanField(
                default=False,
                help_text="Arms this deck for deletion (#2044): deletion from the admin is refused until an admin deliberately turns this on -- and even then only a suspended deck whose staff have been silent for over a year can actually be deleted.",
            ),
        ),
    ]
