# Generated by Django 5.2.16 on 2026-07-22 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0021_tenant_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StripeEventLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.CharField(max_length=255, unique=True)),
                ("event_type", models.CharField(max_length=100)),
                (
                    "schema_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The deck this event was resolved to, when it could be resolved.",
                        max_length=63,
                    ),
                ),
                ("received_on", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
