# Generated by Django 5.2.16 on 2026-08-06 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0022_tenant_can_delete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="can_delete",
            field=models.BooleanField(
                default=False,
                help_text="Arms this deck for deletion (#2044): deletion from the admin is refused until an admin deliberately turns this on -- and even then only a deck that has been suspended for over a year, counted from when its owner was first sent the suspension notice, can actually be deleted.",
            ),
        ),
    ]
