# Generated by Django 5.2.16 on 2026-08-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0024_stripeeventlog"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tenant",
            name="max_quests",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="owner_email",
        ),
        migrations.RemoveField(
            model_name="tenant",
            name="owner_full_name",
        ),
        migrations.AlterField(
            model_name="tenant",
            name="quest_count",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="This is a cached field: the number of quests currently available on the deck (published, past their start date, not expired, not archived, and in an active campaign or no campaign)",
            ),
        ),
    ]
