# Generated by Django 5.2.17 on 2026-08-09 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0025_remove_tenant_max_quests_remove_tenant_owner_email_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReleaseNotification",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=20, unique=True)),
                (
                    "discussion_url",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "notified",
                    models.BooleanField(
                        default=True,
                        help_text="False for the baseline row recorded on the first poll (no notification sent).",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
