# Generated by Django 5.2.17 on 2026-08-17 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0026_releasenotification"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_portal_configuration_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The Billing Portal configuration (bpc_...) whose headline names this deck, created automatically on the owner's first portal visit. Clear it to have the next portal visit rebuild the configuration from the account default (e.g. after changing the default's features in the Stripe dashboard).",
                max_length=255,
            ),
        ),
    ]
