# Generated by Django 5.2.17 on 2026-08-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0027_tenant_stripe_portal_configuration_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="deletion_requested_by",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Who asked (their username at the time of the request), for the audit trail.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="tenant",
            name="deletion_requested_on",
            field=models.DateField(
                blank=True,
                editable=False,
                help_text="When the deck owner asked for this deck to be deleted; blank = no standing request. Set and cleared by the owner from the deck's subscription page.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="can_delete",
            field=models.BooleanField(
                default=False,
                help_text="Arms this deck for deletion: deletion from the admin is refused until an admin deliberately turns this on -- and even then only a suspended deck whose owner has requested deletion, or one that has been suspended for over a year (counted from when its owner was first sent the suspension notice), can actually be deleted.",
            ),
        ),
    ]
