# Generated by Django 5.2.17 on 2026-08-23 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0028_tenant_deletion_requested_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="stripe_auto_renews",
            field=models.BooleanField(
                default=False,
                editable=False,
                help_text="Whether Stripe says the linked subscription bills again on its own. Cleared when the owner sets it to cancel at period end, when a renewal starts failing, and on decks with no Stripe subscription. Synced from Stripe, never edited here.",
            ),
        ),
        migrations.AlterField(
            model_name="decknotice",
            name="kind",
            field=models.CharField(
                choices=[
                    ("expiry", "Trial/subscription expiry reminder"),
                    ("renewal", "Subscription auto-renewal reminder"),
                    ("limit", "Current-student limit warning"),
                    ("suspended", "Deck suspended"),
                    ("payment_failed", "Payment failed"),
                ],
                max_length=20,
            ),
        ),
    ]
