# Generated by Django 5.2.17 on 2026-08-23 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0029_tenant_stripe_auto_renews_alter_decknotice_kind"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decknotice",
            name="threshold",
            field=models.CharField(
                help_text="Which step of the cadence fired: 'd30'/'d14'/'d7'/'d1', 'upcoming', 'pct80'/'pct100', 'suspended', or 'invoice'.",
                max_length=20,
            ),
        ),
    ]
