# Generated by Django 5.2.17 on 2026-10-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenant", "0030_decknotice_threshold_help"),
    ]

    operations = [
        migrations.AlterField(
            model_name="decknotice",
            name="period_key",
            field=models.CharField(
                help_text="The deadline (expiry/suspension) or semester (limit notices) this notice was about;             a new value re-arms the threshold.",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="decknotice",
            name="threshold",
            field=models.CharField(
                help_text="Which step of the cadence fired: 'd30'/'d14'/'d7'/'d1', 'upcoming', 'pct90'/'pct95'/'one-seat-left'/'pct100', 'suspended', or 'invoice'.",
                max_length=20,
            ),
        ),
    ]
