"""
Django settings for hackerspace_online project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

#root of project
BASE_DIR = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Generate a key before production: http://www.miniwebtool.com/django-secret-key-generator/
SECRET_KEY_REMOVE = ''

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#enter proper host names
ALLOWED_HOSTS = [www.mydomain.com, mydomain.com]


EMAIL_HOST = ''
EMAIL_HOST_USER = ''
EMAIL_HOST_PASSWORD =""
EMAIL_PORT = 587
EMAIL_USE_TLS = True


# Application definition

# see settings/base.py
# INSTALLED_APPS += (
#     'myProductionOnlyApp',
# )


# see settings/base.[y
# MIDDLEWARE_CLASSES += (
#     'myProductionOnlyMiddlewareClasses',
# )

# see settings/base.py
# ROOT_URLCONF = 'hackerspace_online.urls'

# see settings/base.py
# TEMPLATES = [
#     {
#         'BACKEND': 'django.template.backends.django.DjangoTemplates',
#         'DIRS': [os.path.join(BASE_DIR, 'templates')],
#         'APP_DIRS': True,
#         'OPTIONS': {
#             'context_processors': [
#                 'django.template.context_processors.debug',
#                 'django.template.context_processors.request',
#                 'django.contrib.auth.context_processors.auth',
#                 'django.contrib.messages.context_processors.messages',
#
#                 # "allauth" specific context processors
#                 'allauth.account.context_processors.account',
#                 'allauth.socialaccount.context_processors.socialaccount'
#             ],
#         },
#     },
# ]

AUTHENTICATION_BACKENDS = (

    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by e-mail
    'allauth.account.auth_backends.AuthenticationBackend',

)

WSGI_APPLICATION = 'hackerspace_online.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

# NEED TO UPDATE TO POSTGRESQL FOR PRODUCTION
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
# see settings/base.py

# Static files (CSS, JavaScript, Images) ####################
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'

#where static files are collected with the collect_static command
STATIC_ROOT = "/var/www/somedir/static/"

# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, "static_in_project",  "our_static"),
#     # os.path.join(BASE_DIR, "static_in_venv"),
#     # '/var/www/static/',
# )

MEDIA_URL = "/media/"
#where media files are saved, e.g. ImageField
MEDIA_ROOT = "/var/www/somedir/media/"

# END STATIC #######################################
