# Generated by Django 5.2.17 on 2026-08-24 17:32

import re

import django.core.validators
from django.db import migrations, models


# A whole "fa-<x>" class token, made of the ASCII lowercase letters, digits and
# hyphens every Font Awesome 4.7.0 class name is made of, and not running on into a
# longer word. Found anywhere in the value, so a whole <i class='fa fa-star'></i>
# someone pasted into the field still yields its icon; the trailing guard is what
# keeps a value like "fa-user_name" from being read as the class "fa-user".
_FA_TOKEN_RE = re.compile(r"fa-[a-z0-9-]+(?![\w-])")

# The shape the field accepts, the pattern its validator carries, requiring a name.
# The reduced name is checked against it, so this migration cannot leave a value the
# field would refuse.
_ICON_NAME_RE = re.compile(r"(?!fa-)[a-z0-9-]+")

# Font Awesome 4.7.0 classes that modify an icon rather than name one, so a value
# like "fa fa-fw fa-star" is read as the icon "star" and not as "fw". Matched whole,
# so real icon names that merely begin the same way ("fa-spinner", "fa-life-ring",
# "fa-stack-overflow") are still read as icons.
_FA_MODIFIERS = frozenset((
    "fa-lg", "fa-2x", "fa-3x", "fa-4x", "fa-5x", "fa-fw", "fa-ul", "fa-li",
    "fa-border", "fa-spin", "fa-pulse", "fa-inverse",
    "fa-stack", "fa-stack-1x", "fa-stack-2x",
))

# The modifier families whose class name carries a value: fa-pull-left,
# fa-rotate-90, fa-flip-horizontal, and so on. No 4.7.0 icon name starts with one.
_FA_MODIFIER_FAMILIES = ("fa-pull-", "fa-rotate-", "fa-flip-")


def _is_modifier(token):
    """True if a "fa-<x>" token is a modifier/sizing class, not an icon name."""
    return token in _FA_MODIFIERS or token.startswith(_FA_MODIFIER_FAMILIES)


def bare_fa_icon_name(raw):
    """Reduce a stored ``fa_icon`` value to the bare Font Awesome icon name.

    Kept inside the migration (not imported from application code) so this one-time
    data transformation stays frozen, the same reason ``courses.0030`` carries its own
    copy of the splitter it needed.

    ``"fa-gift"`` -> ``"gift"``, ``"fa fa-gift"`` -> ``"gift"``, an already-bare
    ``"gift"`` -> ``"gift"``, and a value carrying sizing classes ``"fa-star fa-lg"``
    -> ``"star"`` (these fields have never had anywhere to keep modifier classes, so
    they are dropped). Empty values, unparseable ones, and any whose name the field
    would refuse (``"fa-user_name"``, ``"fa-fa-gift"``) give ``""``.
    """
    fa_tokens = _FA_TOKEN_RE.findall(raw or "")

    if not fa_tokens:
        # No "fa-" token: an already-bare name like "star-o" (ignore a stray "fa").
        # Only accept a lone, clean token; anything else is left unset rather than
        # writing a junk value into the field.
        words = [word for word in (raw or "").split() if word != "fa"]
        return words[0] if len(words) == 1 and _ICON_NAME_RE.fullmatch(words[0]) else ""

    for token in fa_tokens:
        if not _is_modifier(token):
            name = token[len("fa-"):]
            # A doubled prefix ("fa-fa-gift") would leave a name the field refuses.
            return name if _ICON_NAME_RE.fullmatch(name) else ""
    return ""


def normalize_fa_icon_names(apps, schema_editor):
    """Reduce every menu item icon to the bare Font Awesome name the icon picker writes.

    Menu items were already documented as holding a bare name, so this only catches the
    ones where a user typed the "fa-" prefix anyway (which rendered as a blank icon,
    since the template already prefixed it).
    """
    MenuItem = apps.get_model("utilities", "MenuItem")
    for menu_item in MenuItem.objects.exclude(fa_icon=""):
        name = bare_fa_icon_name(menu_item.fa_icon)
        if name != menu_item.fa_icon:
            menu_item.fa_icon = name
            menu_item.save(update_fields=["fa_icon"])


class Migration(migrations.Migration):

    dependencies = [
        ("utilities", "0002_alter_menuitem_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="fa_icon",
            field=models.CharField(
                default="link",
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options, or see the full list of <a target="_blank" rel="noopener" href="https://fontawesome.com/v4.7.0/icons/">Font Awesome 4.7.0 icons</a>.',
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!fa-)[a-z0-9-]*$",
                        'Enter a single Font Awesome icon name in lowercase, e.g. "star" (no "fa-" prefix, no spaces).',
                    )
                ],
            ),
        ),
        # Irreversible on purpose: the bare name is what this field was always meant
        # to hold, so there is no earlier shape to put back.
        migrations.RunPython(normalize_fa_icon_names, migrations.RunPython.noop),
    ]
