# Generated by Django 3.2.18 on 2023-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_side_menu',
            field=models.BooleanField(default=False, help_text='If true, this will be displayed in the side menu'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='label',
            field=models.CharField(help_text='This is the text that will appear for the menu item.', max_length=25, unique=True),
        ),
    ]
