# Generated by Django 3.2.18 on 2023-08-15 03:50

from django.db import migrations, models
import django.db.models.constraints


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_menuitem_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_side_menu',
            field=models.BooleanField(default=False, help_text='If true, this will be displayed in the side menu'),
        ),
        migrations.AddConstraint(
            model_name='menuitem',
            constraint=models.UniqueConstraint(deferrable=django.db.models.constraints.Deferrable['DEFERRED'], fields=('label', 'is_side_menu'), name='unique_menu_item_label'),
        ),
    ]
