# Generated by Django 1.11.17 on 2018-12-28 03:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import profile_manager.models
import re
import utilities.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, default=None, help_text='You can leave this blank, or enter anything you like here.', max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('first_name', models.CharField(help_text='Use the first name that matches your school records.', max_length=50, null=True)),
                ('last_name', models.CharField(help_text='Use the last name that matches your school records.', max_length=50, null=True)),
                ('preferred_name', models.CharField(blank=True, help_text='If you would prefer your teacher to call you by a name other than                                       the first name you entered above, put it here.', max_length=50, null=True, verbose_name='Preferred first name')),
                ('student_number', models.PositiveIntegerField(null=True, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_student_number', message='Invalid student number.', regex='^(9[89])(\\d{5})$')])),
                ('grad_year', models.PositiveIntegerField(null=True)),
                ('is_test_account', models.BooleanField(default=False, help_text="A test account that won't show up in student lists")),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('intro_tour_completed', models.BooleanField(default=False)),
                ('game_lab_transfer_process_on', models.BooleanField(default=False)),
                ('banned_from_comments', models.BooleanField(default=False)),
                ('xp_cached', models.IntegerField(default=0)),
                ('get_announcements_by_email', models.BooleanField(default=False)),
                ('visible_to_other_students', models.BooleanField(default=False, help_text='Your marks will be visible to other students through the student list.')),
                ('preferred_internal_only', models.BooleanField(default=False, help_text="Check this if you don't want your preferred first name used in any public areas.", verbose_name='Use preferred first name internally only')),
                ('dark_theme', models.BooleanField(default=False)),
                ('hidden_quests', models.CharField(blank=True, max_length=255, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')])),
                ('is_TA', models.BooleanField(default=False, help_text='TAs can create new quests for teacher approval.')),
                ('custom_stylesheet', utilities.models.RestrictedFileField(blank=True, help_text='ADVANCED: A CSS file to customize the Hackerspace.  You can use                                                     this to tweak something, or create a completely new theme.', null=True, upload_to=profile_manager.models.user_directory_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
    ]
