# Generated by Django 2.0.13 on 2019-07-30 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0003_auto_20190721_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_notifications_by_email',
            field=models.BooleanField(default=False, help_text='If you provided an email address on your profile, you will get unread notifications emailed to you once per day.'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='get_announcements_by_email',
            field=models.BooleanField(default=False, help_text='If you provided an email address on your profile, you will get announcements emailed to you when they are published.'),
        ),
    ]
