# Generated by Django 2.0.13 on 2019-08-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0004_auto_20190729_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='get_messages_by_email',
            field=models.BooleanField(default=True, help_text='If your teacher sends you a message, get an instance email.'),
        ),
    ]
