# Generated by Django 2.2.12 on 2020-04-16 00:42

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0007_auto_20200104_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_quests',
            field=models.CharField(blank=True, max_length=1023, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
