# Generated by Django 2.2.11 on 2020-03-26 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile_manager', '0007_auto_20200104_1934'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherStudentProfileProxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_manager.Profile')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proxy_students', to=settings.AUTH_USER_MODEL)),
            ]
        ),
        migrations.AddField(
            model_name='profile',
            name='teachers',
            field=models.ManyToManyField(related_name='students', through='profile_manager.TeacherStudentProfileProxy', to=settings.AUTH_USER_MODEL),
        ),
    ]
