# Generated by Django 2.2.12 on 2020-04-26 03:52

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0008_auto_20200415_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='hidden_quests',
            field=models.CharField(blank=True, max_length=1023, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
