# Generated by Django 2.2.11 on 2020-03-26 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0008_auto_20200326_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherstudentprofileproxy',
            name='is_creator',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherstudentprofileproxy',
            name='is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
