# Generated by Django 2.2.13 on 2020-07-23 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0010_auto_20200529_1705'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_number',
        ),
    ]
