# Generated by Django 2.2.14 on 2020-08-08 01:42

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0011_remove_profile_student_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=0, size=[256, 256], upload_to='avatars/'),
        ),
    ]
