# Generated by Django 2.2.15 on 2020-08-20 01:34

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0013_auto_20200818_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=100, size=[256, 256], upload_to='avatars/'),
        ),
    ]
