# Generated by Django 3.2.17 on 2023-06-29 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0015_auto_20200907_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_of_last_submission',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
