# Generated by Django 3.2.17 on 2023-06-29 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0016_profile_time_of_last_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mark_cached',
            field=models.DecimalField(blank=True, decimal_places=1, default=None, max_digits=4, null=True),
        ),
    ]
