# Generated by Django 3.2.18 on 2024-01-07 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_manager', '0017_profile_mark_cached'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
