# Generated by Django 5.2.16 on 2026-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0019_auto_20240807_1432"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="mark_cached",
            field=models.DecimalField(
                blank=True, decimal_places=1, default=None, max_digits=6, null=True
            ),
        ),
    ]
