# Generated by Django 5.2.17 on 2026-08-07 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profile_manager", "0020_alter_profile_mark_cached"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="intro_tour_completed",
        ),
    ]
