# Generated by Django 5.2.17 on 2026-10-08 04:51

from django.conf import settings
from django.db import migrations, models
from django.db.models import OuterRef, Subquery


def start_from_last_login(apps, schema_editor):
    """Start each profile's last activity at the person's last sign-in, the latest time on record.

    Without it every existing profile would show no activity until the person next used the deck.
    """
    Profile = apps.get_model("profile_manager", "Profile")
    User = apps.get_model(settings.AUTH_USER_MODEL)
    last_login = User.objects.filter(pk=OuterRef("user_id")).values("last_login")[:1]
    Profile.objects.filter(last_active__isnull=True).update(last_active=Subquery(last_login))


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profile_manager", "0021_remove_profile_intro_tour_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="last_active",
            field=models.DateTimeField(
                blank=True,
                help_text="When this person last used the deck, recorded at most once an hour.",
                null=True,
            ),
        ),
        migrations.RunPython(start_from_last_login, migrations.RunPython.noop),
    ]
