# Generated by Django 4.2.30 on 2026-07-17 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0002_auto_20211130_2003"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(blank=True),
        ),
    ]
