# Generated by Django 4.2.19 on 2025-02-11 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20211130_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='paste_detected',
            field=models.BooleanField(default=False),
        ),
    ]
