# Generated by Django 5.2.17 on 2026-09-30 17:18

import utilities.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0003_alter_comment_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="docfile",
            field=models.FileField(
                max_length=255,
                upload_to=utilities.uploads.UploadToOwnFolder("documents/%Y/%m/%d"),
            ),
        ),
    ]
