# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2018-12-28 03:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Briefly describes the suggestion', max_length=50)),
                ('description', models.TextField(help_text='A detailed explanation includes WHAT the suggestion is,         WHY the suggestions will improve the Hackerspace,         and HOW Mr C can implement the suggestion. ')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveIntegerField(choices=[(1, 'awaiting approval'), (2, 'approved'), (3, 'completed'), (4, 'unlikely'), (5, 'not approved')], default=1)),
                ('status_timestamp', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vote', models.SmallIntegerField(help_text='up vote is +1, down vote is -1')),
                ('suggestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='suggestions.Suggestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
