# Generated by Django 2.0.13 on 2019-08-09 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BadgeRarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The unique name or label for this rarity of badge, e.g. 'Legendary'", max_length=50, unique=True)),
                ('percentile', models.FloatField(help_text='A number from 0.1% (or less) to 100.0% indicating the rarity of the badge.  For example:             10.0% would mean badges that <10.0% of users have earned will be assigned this rarity, unless             it falls into the next more rare category (such as 5.0%).  A value of 100 will catch all badges.', unique=True)),
                ('color', models.CharField(default='gray', help_text='An HTML color name "gray" or hex value in the format: "#7b7b7b;"', max_length=50)),
                ('fa_icon', models.CharField(default='fa-certificate', help_text='A font-awesome icon to represent this rarity, should begin with "fa-".  See here for             options: "https://faicons.com"', max_length=50)),
            ],
        ),
    ]
