# Generated by Django 2.0.13 on 2019-08-09 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0002_badgerarity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badgerarity',
            options={'ordering': ['percentile'], 'verbose_name': 'Badge Rarity', 'verbose_name_plural': 'Badge Rarities'},
        ),
    ]
