# Generated by Django 2.2.12 on 2020-05-09 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0003_auto_20190809_1136'),
    ]

    operations = [
        #migrations.RunPython(load_initial_data),
    ]
