# Generated by Django 2.2.12 on 2020-05-28 05:50

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Badge = apps.get_model('badges', 'Badge')
    db_alias = schema_editor.connection.alias
    for row in Badge.objects.using(db_alias).all():
        row.import_id = uuid.uuid4()
        row.save(update_fields=['import_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0006_badge_import_id_1'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
