# Generated by Django 2.2.12 on 2020-05-28 05:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0007_badge_import_id_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='import_id',
            field=models.UUIDField(
                default=uuid.uuid4,
                unique=True,
                help_text='Only edit this if you want to link to a badge in another system so that when importing from that other system, it will update this badge too. Otherwise do not edit this or it will break existing links!'),
        ),
    ]
