# Generated by Django 2.2.12 on 2020-05-09 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0008_badge_import_id_3'),
    ]

    operations = [
        # migrations.RunPython(load_initial_data),
    ]
