# Generated by Django 2.2.13 on 2020-09-01 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0009_badge_initialdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badgeassertion',
            old_name='game_lab_transfer',
            new_name='do_not_grant_xp',
        ),
    ]
