# Generated by Django 2.2.24 on 2022-01-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0011_badge_map_transition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='map_transition',
            field=models.BooleanField(default=False, help_text='Break maps at this badge.  This badge will link to a new map.'),
        ),
    ]
