# Generated by Django 3.2.13 on 2022-06-10 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0012_auto_20220115_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='badge_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='badges.badgetype'),
        ),
    ]
