# Generated by Django 4.2.21 on 2025-07-26 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('badges', '0014_badge_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='active',
            new_name='published',
        ),
    ]
