# Generated by Django 5.2.16 on 2026-08-14 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0015_rename_active_badge_published"),
        ("courses", "0029_semester_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgeassertion",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.semester",
            ),
        ),
    ]
