# Generated by Django 5.2.16 on 2026-08-16 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0016_alter_badgeassertion_semester"),
        ("courses", "0029_semester_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="badgeassertion",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="The course this badge's XP counts toward.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.course",
            ),
        ),
    ]
