# Generated by Django 5.2.17 on 2026-08-24 17:32

import re

import django.core.validators
from django.db import migrations, models


# Every "fa-<x>" class token in a value.
_FA_TOKEN_RE = re.compile(r"fa-[\w-]+")

# Font Awesome 4.7.0 classes that modify an icon rather than name one, so a value
# like "fa fa-fw fa-star" is read as the icon "star" and not as "fw". Matched whole,
# so real icon names that merely begin the same way ("fa-spinner", "fa-life-ring",
# "fa-stack-overflow") are still read as icons.
_FA_MODIFIERS = frozenset((
    "fa-lg", "fa-2x", "fa-3x", "fa-4x", "fa-5x", "fa-fw", "fa-ul", "fa-li",
    "fa-border", "fa-spin", "fa-pulse", "fa-inverse",
    "fa-stack", "fa-stack-1x", "fa-stack-2x",
))

# The modifier families whose class name carries a value: fa-pull-left,
# fa-rotate-90, fa-flip-horizontal, and so on. No 4.7.0 icon name starts with one.
_FA_MODIFIER_FAMILIES = ("fa-pull-", "fa-rotate-", "fa-flip-")


def _is_modifier(token):
    """True if a "fa-<x>" token is a modifier/sizing class, not an icon name."""
    return token in _FA_MODIFIERS or token.startswith(_FA_MODIFIER_FAMILIES)


def bare_fa_icon_name(raw):
    """Reduce a stored ``fa_icon`` value to the bare Font Awesome icon name.

    Kept inside the migration (not imported from application code) so this one-time
    data transformation stays frozen, the same reason ``courses.0030`` carries its own
    copy of the splitter it needed.

    ``"fa-gift"`` -> ``"gift"``, ``"fa fa-gift"`` -> ``"gift"``, an already-bare
    ``"gift"`` -> ``"gift"``, and a value carrying sizing classes ``"fa-star fa-lg"``
    -> ``"star"`` (these fields have never had anywhere to keep modifier classes, so
    they are dropped). Empty or unparseable values give ``""``.
    """
    raw = (raw or "").strip()
    if not raw:
        return ""

    fa_tokens = _FA_TOKEN_RE.findall(raw)
    if not fa_tokens:
        # No "fa-" token: an already-bare name like "star-o" (ignore a stray "fa").
        # Only accept a lone, clean token; anything else is left unset rather than
        # writing a junk value into the field.
        words = [word for word in raw.split() if word and word != "fa"]
        if len(words) == 1 and re.fullmatch(r"[a-z0-9-]+", words[0]):
            return words[0]
        return ""

    for token in fa_tokens:
        if not _is_modifier(token):
            return token[len("fa-"):]
    return ""


def normalize_fa_icon_names(apps, schema_editor):
    """Reduce every badge type and badge rarity icon to the bare Font Awesome name the
    icon picker writes, so these fields hold what ranks and menu items already hold."""
    BadgeType = apps.get_model("badges", "BadgeType")
    for badge_type in BadgeType.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
        name = bare_fa_icon_name(badge_type.fa_icon)
        if name != badge_type.fa_icon:
            badge_type.fa_icon = name
            badge_type.save(update_fields=["fa_icon"])

    BadgeRarity = apps.get_model("badges", "BadgeRarity")
    for rarity in BadgeRarity.objects.all():
        # A rarity always shows an icon, so an unparseable value falls back to the
        # generic badge icon the field defaults to rather than being left empty.
        name = bare_fa_icon_name(rarity.fa_icon) or "certificate"
        if name != rarity.fa_icon:
            rarity.fa_icon = name
            rarity.save(update_fields=["fa_icon"])


def restore_fa_icon_prefixes(apps, schema_editor):
    """Reverse: put the "fa-" prefix back on both fields, so they round-trip to the
    shape the older code rendered if this migration is unapplied."""
    for model_name in ("BadgeType", "BadgeRarity"):
        model = apps.get_model("badges", model_name)
        for obj in model.objects.exclude(fa_icon__isnull=True).exclude(fa_icon=""):
            if not obj.fa_icon.startswith("fa-"):
                obj.fa_icon = "fa-" + obj.fa_icon
                obj.save(update_fields=["fa_icon"])


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0017_badgeassertion_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgerarity",
            name="fa_icon",
            field=models.CharField(
                default="certificate",
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options, or see the full list of <a target="_blank" rel="noopener" href="https://fontawesome.com/v4.7.0/icons/">Font Awesome 4.7.0 icons</a>.',
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!fa-)[a-z0-9-]*$",
                        'Enter a single Font Awesome icon name in lowercase, e.g. "star" (no "fa-" prefix, no spaces).',
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="badgetype",
            name="fa_icon",
            field=models.CharField(
                blank=True,
                help_text='A Font Awesome icon name, e.g. "star". Use the picker to browse the options, or see the full list of <a target="_blank" rel="noopener" href="https://fontawesome.com/v4.7.0/icons/">Font Awesome 4.7.0 icons</a>.',
                max_length=50,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!fa-)[a-z0-9-]*$",
                        'Enter a single Font Awesome icon name in lowercase, e.g. "star" (no "fa-" prefix, no spaces).',
                    )
                ],
            ),
        ),
        migrations.RunPython(
            normalize_fa_icon_names,
            restore_fa_icon_prefixes,
        ),
    ]
