# Generated by Django 5.2.17 on 2026-09-25 00:40

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badges", "0018_normalize_badge_fa_icon_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="badgerarity",
            name="color",
            field=models.CharField(
                default="gray",
                help_text='An HTML color name "gray" or hex value in the format: "#7b7b7b;"',
                max_length=50,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^\\s*(#[0-9A-Fa-f]{3,8}|[A-Za-z]+)\\s*;?\\s*$"),
                        'Enter an HTML color name, e.g. "gray", or a hex value, e.g. "#7b7b7b".',
                    )
                ],
            ),
        ),
    ]
