from datetime import timedelta
from email.utils import formataddr
from model_bakery import baker
from unittest.mock import patch

from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.core.mail import EmailMultiAlternatives
from django.test import override_settings
from django.utils import timezone
from django_tenants.utils import get_tenant_model

from hackerspace_online.tests.utils import ByteDeckTenantTestCase
from notifications import tasks
from notifications.models import Notification
from notifications.tasks import generate_notification_email, get_notification_emails, delete_old_notifications
from siteconfig.models import SiteConfig

User = get_user_model()


class NotificationTasksTests(ByteDeckTenantTestCase):
    """ Run tasks asyncronously with apply() """

    @classmethod
    def setUpTestData(cls):
        """Create a teacher, two students, the AI user, and course enrollments for notification tasks."""
        cls.sem = SiteConfig.get().active_semester
        # need a teacher before students can be created or the profile creation will fail when trying to notify
        cls.test_teacher = User.objects.create_user('test_teacher', is_staff=True)
        cls.test_student1 = User.objects.create_user('test_student', email="student@email.com")
        cls.test_student2 = baker.make(User, email="student2@email.com")

        cls.ai_user, _ = User.objects.get_or_create(
            pk=SiteConfig.get().deck_ai.pk,
            defaults={
                'username': "Autogenerated AI",
            },
        )

        baker.make('courses.CourseStudent', user=cls.test_student1, semester=cls.sem)
        baker.make('courses.CourseStudent', user=cls.test_student2, semester=cls.sem)

    def setUp(self):
        """Set the deck's short name per-test (SiteConfig writes populate the cross-test cache)."""
        # SiteConfig writes populate the cross-test SiteConfig cache, so keep this per-test
        config = SiteConfig.get()
        config.site_name_short = "Deck"
        config.save()

    def test_get_notification_emails__respects_prefs_and_enrollment(self):
        """Only enrolled students with email notifications enabled and unread notifications get an email."""
        root_url = f'https://{self.get_test_tenant_domain()}'

        # 0 notifications to start
        emails = get_notification_emails(root_url)
        self.assertEqual(type(emails), list)
        self.assertEqual(len(emails), 0)

        course = baker.make('courses.Course')
        semester = SiteConfig.get().active_semester

        # A valid sender for the notifications. Without an explicit GFK target,
        # baker fills sender_content_type/sender_object_id with a random installed
        # model (see CLAUDE.md) -- which can be a table-less throwaway test model,
        # making str(notification) crash when the email task renders it.
        user_ct = ContentType.objects.get_for_model(User)

        # Create a notification for student 1, but they have emails turned off by default
        notification1 = baker.make(
            Notification, recipient=self.test_student1,
            sender_content_type=user_ct, sender_object_id=self.test_teacher.id,
        )
        emails = get_notification_emails(root_url)
        self.assertEqual(len(emails), 0)

        # Turn on notification emails for student1, now it should appear and add them to the list of emails
        from allauth.account.models import EmailAddress

        EmailAddress.objects.create(user=self.test_student1, email=self.test_student1.email, verified=True, primary=True)
        baker.make('courses.CourseStudent', user=self.test_student1, course=course, semester=semester)
        self.test_student1.profile.get_notifications_by_email = True
        self.test_student1.profile.save()

        emails = get_notification_emails(root_url)

        self.assertEqual(len(emails), 1)
        self.assertEqual(emails[0].to, [self.test_student1.email])

        # Turn on notification emails for student2, should still only be 1 (from the test_student1)
        EmailAddress.objects.create(user=self.test_student2, email=self.test_student2.email, verified=True, primary=True)
        baker.make('courses.CourseStudent', user=self.test_student2, course=course, semester=semester)
        self.test_student2.profile.get_notifications_by_email = True
        self.test_student2.profile.save()

        emails = get_notification_emails(root_url)
        self.assertEqual(len(emails), 1)
        self.assertEqual(emails[0].to, [self.test_student1.email])

        # Make a bunch of notifications for student2, so now we should have 2 emails
        baker.make(
            Notification, recipient=self.test_student2, _quantity=10,
            sender_content_type=user_ct, sender_object_id=self.test_teacher.id,
        )
        emails = get_notification_emails(root_url)

        self.assertEqual(len(emails), 2)
        self.assertEqual(emails[0].to, [self.test_student1.email])
        self.assertEqual(emails[1].to, [self.test_student2.email])

        # mark the original notification as read, so only student2 email now
        notification1.unread = False
        notification1.save()
        emails = get_notification_emails(root_url)
        self.assertEqual(len(emails), 1)
        self.assertEqual(emails[0].to, [self.test_student2.email])

    def _make_two_eligible_recipients(self):
        """Give both students an unread notification, a verified email, an enrollment,
        and the email-notifications preference, so the digest task builds two emails.

        Returns:
            tuple: (student1, student2), in mailing-list order.
        """
        from allauth.account.models import EmailAddress

        course = baker.make('courses.Course')
        semester = SiteConfig.get().active_semester
        user_ct = ContentType.objects.get_for_model(User)
        for student in (self.test_student1, self.test_student2):
            baker.make(
                Notification, recipient=student,
                sender_content_type=user_ct, sender_object_id=self.test_teacher.id,
            )
            EmailAddress.objects.create(user=student, email=student.email, verified=True, primary=True)
            baker.make('courses.CourseStudent', user=student, course=course, semester=semester)
            student.profile.get_notifications_by_email = True
            student.profile.save()
        return self.test_student1, self.test_student2

    def test_get_notification_emails__only_usernames_filters_and_tags(self):
        """The retry filter builds just the named users' digests, and every built
        email carries its recipient's username for the send task's retry plumbing."""
        student1, student2 = self._make_two_eligible_recipients()
        root_url = f'https://{self.get_test_tenant_domain()}'

        emails = get_notification_emails(root_url)
        self.assertEqual(len(emails), 2)
        self.assertEqual({e.recipient_username for e in emails}, {student1.username, student2.username})

        emails = get_notification_emails(root_url, only_usernames=[student2.username])
        self.assertEqual(len(emails), 1)
        self.assertEqual(emails[0].recipient_username, student2.username)

    def test_email_task__permanent_refusal_drops_only_that_user(self):
        """A 5xx refusal for one user's digest is logged and skipped: the rest of
        the batch still sends, the task succeeds, and nothing is retried."""
        import smtplib
        from unittest.mock import Mock

        self._make_two_eligible_recipients()
        root_url = f'https://{self.get_test_tenant_domain()}'

        connection = Mock()
        connection.send_messages.side_effect = [
            smtplib.SMTPResponseException(550, b'no such user'), 1]
        with patch('notifications.tasks.mail.get_connection', return_value=connection):
            task_result = tasks.email_notifications_to_users_on_schema.apply(
                kwargs={'root_url': root_url})
        self.assertTrue(task_result.successful())
        self.assertEqual(task_result.result, 'Sent 1 notification emails, dropped 1 permanently refused')
        self.assertEqual(connection.send_messages.call_count, 2)

    def test_email_task__temporary_failure_retries_only_the_unsent(self):
        """A 4xx rejection (Gmail's 451 throttle) never aborts the batch: the other
        digests still send, and the task retries with ONLY the throttled users, so
        nobody already emailed gets a duplicate (production find, 2026-08-18)."""
        import smtplib

        from celery.exceptions import Retry
        from unittest.mock import Mock

        student2 = self._make_two_eligible_recipients()[1]
        root_url = f'https://{self.get_test_tenant_domain()}'

        connection = Mock()
        connection.send_messages.side_effect = [
            1, smtplib.SMTPDataError(451, b'4.3.0 Mail server temporarily rejected message')]
        task = tasks.email_notifications_to_users_on_schema
        with patch('notifications.tasks.mail.get_connection', return_value=connection), \
                patch.object(task, 'retry', side_effect=Retry('retry scheduled')) as mock_retry:
            task_result = task.apply(kwargs={'root_url': root_url})
        self.assertFalse(task_result.successful())
        mock_retry.assert_called_once()
        kwargs = mock_retry.call_args.kwargs
        self.assertEqual(kwargs['kwargs'], {'root_url': root_url, 'only_usernames': [student2.username]})
        self.assertEqual(kwargs['countdown'], 300)

    def test_email_task__disconnect_is_retried_as_temporary(self):
        """A dead SMTP session (disconnect mid-batch) counts as temporary: the
        affected user lands in the retry set rather than losing their digest.
        This path is deliberately at-least-once: the server may have accepted
        the message before the connection died, and a rare duplicate digest
        beats a silently lost one (the status-rejection paths cannot
        duplicate, since a refusal is unambiguous)."""
        import smtplib

        from celery.exceptions import Retry
        from unittest.mock import Mock

        student1 = self._make_two_eligible_recipients()[0]
        root_url = f'https://{self.get_test_tenant_domain()}'

        connection = Mock()
        connection.send_messages.side_effect = [smtplib.SMTPServerDisconnected('gone'), 1]
        task = tasks.email_notifications_to_users_on_schema
        with patch('notifications.tasks.mail.get_connection', return_value=connection), \
                patch.object(task, 'retry', side_effect=Retry('retry scheduled')) as mock_retry:
            task_result = task.apply(kwargs={'root_url': root_url})
        self.assertFalse(task_result.successful())
        self.assertEqual(
            mock_retry.call_args.kwargs['kwargs'],
            {'root_url': root_url, 'only_usernames': [student1.username]})

    def test_email_task__recipient_refused_4xx_is_retried(self):
        """A per-recipient 4xx refusal (SMTPRecipientsRefused) counts as temporary:
        the refused user lands in the retry set, like the one-code 4xx rejection."""
        import smtplib

        from celery.exceptions import Retry
        from unittest.mock import Mock

        student2 = self._make_two_eligible_recipients()[1]
        root_url = f'https://{self.get_test_tenant_domain()}'

        connection = Mock()
        connection.send_messages.side_effect = [
            1, smtplib.SMTPRecipientsRefused({student2.email: (450, b'4.2.1 mailbox busy')})]
        task = tasks.email_notifications_to_users_on_schema
        with patch('notifications.tasks.mail.get_connection', return_value=connection), \
                patch.object(task, 'retry', side_effect=Retry('retry scheduled')) as mock_retry:
            task_result = task.apply(kwargs={'root_url': root_url})
        self.assertFalse(task_result.successful())
        self.assertEqual(
            mock_retry.call_args.kwargs['kwargs'],
            {'root_url': root_url, 'only_usernames': [student2.username]})

    def test_email_task__recipient_refused_5xx_drops_only_that_user(self):
        """A per-recipient 5xx refusal (SMTPRecipientsRefused) is permanent: that
        user's digest is logged and dropped, the rest of the batch still sends,
        and nothing is retried."""
        import smtplib
        from unittest.mock import Mock

        self._make_two_eligible_recipients()
        root_url = f'https://{self.get_test_tenant_domain()}'

        connection = Mock()
        connection.send_messages.side_effect = [
            smtplib.SMTPRecipientsRefused({self.test_student1.email: (550, b'5.1.1 user unknown')}), 1]
        with patch('notifications.tasks.mail.get_connection', return_value=connection):
            task_result = tasks.email_notifications_to_users_on_schema.apply(
                kwargs={'root_url': root_url})
        self.assertTrue(task_result.successful())
        self.assertEqual(task_result.result, 'Sent 1 notification emails, dropped 1 permanently refused')
        self.assertEqual(connection.send_messages.call_count, 2)

    def test_email_notification_to_users_on_all_schemas__runs_successfully(self):
        """The all-schemas email task completes successfully when applied."""
        task_result = tasks.email_notification_to_users_on_all_schemas.apply()
        self.assertTrue(task_result.successful())

    def test_email_notifications_to_users_on_schema__runs_successfully(self):
        """The per-schema email task completes successfully when applied."""
        task_result = tasks.email_notifications_to_users_on_schema.apply(
            kwargs={
                "root_url": "https://test.com",
            }
        )
        self.assertTrue(task_result.successful())

    def test_generate_notification_email__student(self):
        """ Test that the content of a notification email is correct """
        notifications = baker.make(
            Notification, recipient=self.test_student1, _quantity=2,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )

        root_url = 'https://test.com'
        email = generate_notification_email(self.test_student1, root_url)

        self.assertEqual(type(email), EmailMultiAlternatives)
        self.assertEqual(email.to, [self.test_student1.email])
        # Subject names the deck's domain (the host of root_url) so recipients can tell decks apart (#2338)
        self.assertEqual(email.subject, "Notifications from test.com")

        # https://stackoverflow.com/questions/62958111/how-to-display-html-content-of-an-emailmultialternatives-mail-object
        html_content = email.alternatives[0][0]

        self.assertNotIn("Quest submissions awaiting your approval", html_content)  # Teachers only

        self.assertIn("Unread notifications:", html_content)
        self.assertIn(str(notifications[0]), html_content)  # Links to notifications
        self.assertIn(str(notifications[1]), html_content)  # Links to notifications

    @override_settings(DEFAULT_FROM_EMAIL="noreply@bytedeck.com")
    def test_generate_notification_email__from_names_the_deck(self):
        """The From header shows the deck's domain as the sender name while keeping the
        configured sending address, so recipients can tell which deck it's from (#2338)."""
        baker.make(
            Notification, recipient=self.test_student1,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )
        email = generate_notification_email(self.test_student1, "https://test.com")
        self.assertEqual(email.from_email, formataddr(("test.com", "noreply@bytedeck.com")))

    @override_settings(DEFAULT_FROM_EMAIL="Byte Deck <contact@bytedeck.com>")
    def test_generate_notification_email__from_when_the_setting_carries_its_own_name(self):
        """DEFAULT_FROM_EMAIL is configured with a display name in production, so only its
        address goes under the deck's domain. A header carrying both names is not a valid
        address, and the nightly digest raises ValueError in the Celery task instead of
        being delivered."""
        baker.make(
            Notification, recipient=self.test_student1,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )
        email = generate_notification_email(self.test_student1, "https://test.com")
        self.assertEqual(email.from_email, formataddr(("test.com", "contact@bytedeck.com")))

    @override_settings(DEFAULT_FROM_EMAIL="")
    def test_generate_notification_email__from_falls_back_when_unconfigured(self):
        """With no DEFAULT_FROM_EMAIL configured, the From is left to Django's default (#2338)."""
        baker.make(
            Notification, recipient=self.test_student1,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )
        email = generate_notification_email(self.test_student1, "https://test.com")
        # from_email=None -> EmailMessage substitutes settings.DEFAULT_FROM_EMAIL (here "")
        self.assertEqual(email.from_email, "")

    def test_generate_notification_email__staff(self):
        """ Test that staff notification emails include quests awaiting approval """
        notification = baker.make(
            Notification, recipient=self.test_teacher,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )
        root_url = 'https://test.com'
        sub = baker.make('quest_manager.questsubmission')

        # fake the call to `QuestSubmission.objects.all_awaiting_approval` made within
        # `generate_notification_email` so that it return a submission
        with patch('notifications.tasks.QuestSubmission.objects.all_awaiting_approval', return_value=[sub]):
            email = generate_notification_email(self.test_teacher, root_url)

        self.assertEqual(type(email), EmailMultiAlternatives)
        self.assertEqual(email.to, [self.test_teacher.email])

        # https://stackoverflow.com/questions/62958111/how-to-display-html-content-of-an-emailmultialternatives-mail-object
        html_content = email.alternatives[0][0]
        self.assertIn("Quest submissions awaiting your approval", html_content)  # Teachers only
        self.assertIn(str(sub), html_content)

        self.assertIn("Unread notifications:", html_content)
        self.assertIn(str(notification), html_content)  # Links to notifications

    def test_generate_notification_email__non_enrolled_student_returns_none(self):
        """A non-staff student not enrolled in a current course gets no notification email, even
        when they have unread notifications that would otherwise generate one."""
        non_enrolled_student = baker.make(User, is_staff=False)  # not staff, no course
        # an unread notification, so the None result must come from the enrollment guard
        # rather than the "no content to send" branch
        baker.make(
            Notification, recipient=non_enrolled_student,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )
        self.assertIsNone(generate_notification_email(non_enrolled_student, 'https://test.com'))

    def test_get_notification_emails__skips_inactive_students(self):
        """A student not enrolled in any course gets no email even with notifications enabled."""
        root_url = 'https://test.com'

        # 0 notifications to start
        emails = get_notification_emails(root_url)
        self.assertEqual(type(emails), list)
        self.assertEqual(len(emails), 0)

        # Create a noficiation for 1 student that has no course but have emails turned on
        inactive_student = baker.make(User)
        baker.make(
            Notification, recipient=inactive_student,
            sender_content_type=ContentType.objects.get_for_model(User), sender_object_id=self.test_teacher.id,
        )

        inactive_student.profile.get_notifications_by_email = True
        inactive_student.profile.save()

        # Should not get email because they are not enrolled in any courses
        emails = get_notification_emails(root_url)
        self.assertEqual(len(emails), 0)


class DeleteOldNotificationsTestCase(ByteDeckTenantTestCase):
    @classmethod
    def setUpTestData(cls):
        """Create one notification older than 3 months and one within 3 months."""
        cls.old_notification = baker.make(
            Notification,
            timestamp=timezone.now() - timedelta(days=90)  # Older than 3 months
        )

        cls.recent_notification = baker.make(
            Notification,
            timestamp=timezone.now() - timedelta(days=89)  # Within 3 months
        )

        cls.notification_count = Notification.objects.count()

    def test_delete_old_notifications__removes_old_keeps_recent(self):
        """Ensure old notifications >90 days are deleted but recent ones remain."""
        delete_old_notifications()

        with self.assertRaises(Notification.DoesNotExist):
            self.old_notification.refresh_from_db()  # Should be deleted

        self.recent_notification.refresh_from_db()  # Should still exist

    @patch('notifications.tasks.delete_old_notifications.delay')
    def test_delete_old_notifications__can_be_scheduled_via_celery(self, mock_task):
        """Ensure the task can be scheduled via Celery."""
        delete_old_notifications.delay()
        mock_task.assert_called_once()

    @patch('notifications.tasks.delete_old_notifications.apply_async')
    def test_delete_old_notifications_for_all_tenants__schedules_per_tenant(self, mock_apply_async):
        """The all-tenants task schedules a per-schema delete for each non-public tenant."""
        result = tasks.delete_old_notifications_for_all_tenants()

        # one scheduled delete per non-public tenant, each on the default queue
        expected_tenants = get_tenant_model().objects.exclude(schema_name='public')
        self.assertEqual(mock_apply_async.call_count, expected_tenants.count())
        self.assertTrue(all(call.kwargs == {'queue': 'default'} for call in mock_apply_async.call_args_list))
        self.assertEqual(result, "Scheduled notifications.tasks.delete_old_notifications for all schemas/tenants")
